In [1]:
import requests
import pandas as pd
import io
import numpy as np
from io import StringIO
import os
from datetime import date, timedelta
pd.set_option("display.max_rows", 100000, "display.max_columns", 100000)

In [2]:
username = os.getenv('WDUSER')
password = os.getenv('WDPASSWORD')

# RaaS Hire Report

In [3]:
hireend = '2022-12-31'
hirestart = '2000-01-01'

In [8]:
hire = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Hires?SupervisoryOrg%21WID=fad8c8a44c4510541494e34161d00311&BPStatus%21WID=b90bc51be01d4ae99b603b02b073714d&BPType%21WID=e6591cf3a39e44f0b01c711957f72e76!26627c6715f84ddba510f25c433aeb2b!bd774409e883445d8a773a92274ece71!08e574a19f6b400fac5dbe71ea854f1d!aaa046227982460f98d5a1ca14f91d2b!1758d7cf019a4c6a827fbba824a2866c!c44ef33941cf425f9d4e27e1403c7670&IncludeSubOrgs=1&EffectiveEnd=2021-12-31-08%3A00&EffectiveStart=2000-01-01-08%3A00&Organization%21WID=fad8c8a44c4510541494e34161d00311&EndDate=2022-12-31-08%3A00&StartDate=2014-01-01-08%3A00&format=csv'
with requests.Session() as s:
    download = s.get(hire, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    hire = pd.read_csv(io.StringIO(decoded_content))
    hire = hire.set_index('Emplid')

C:\Users\DDY17\Anaconda3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (14,63,64,65) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [11]:
#hire = hire.rename(columns={'Job_Change___Hire_Date':'Job Change / Hire', 'Job_Profile':'Job Profile', 'Job_Requisition':'Job Requisition',
#       'Position_Number':'Position Number', 'Job_Requisition_Status':'Job Requisition Status', 'Job_Req_Fill_Date':'Job Req Fill Date',
#       'Hiring_Manager':'Hiring Manager', 'Hire_Type':'Hire Type', 'Job_Level':'Job Level', 'Grade':'Grade',
#       'Annual_Salary':'Annual Salary', 'Supervisory_Org':'Supervisory Org',
#       'Business_Area':'Business Area', 'Consolidated_Area':'Consolidated Area',
#       'Age_Group':'Age Group', 'Minority___Non-Minority':'Minority','termination_date':'Termination Date',
#       'Termination_Reason':'Termination Reason'})

In [9]:
print(hire.shape)
hire.head()

(17342, 75)

,Requisition,Position,ReqStatus,ReqOpen,Filled,ReplacementFor,Recruiter,HiringManager,PostingSites,HasInternalPostings,HasExternalPostings,HasAgencyPostings,Initiated,Effective,Worker,Type,HireType,Active,WorkState,AgeGroup,Age,Diverse,Gender,Minority,Veteran,Disability,Grade,GradeProfile,JobLevel,JobCode,JobProfile,AnnualSalary,SupervisoryOrgID,SupervisoryOrg,SupervisoryOrgManager,OrgLevel01ID,OrgLevel01,OrgLevel01Manager,OrgLevel02ID,OrgLevel02,OrgLevel02Manager,OrgLevel03ID,OrgLevel03,OrgLevel03Manager,OrgLevel04ID,OrgLevel04,OrgLevel04Manager,OrgLevel05ID,OrgLevel05,OrgLevel05Manager,OrgLevel06ID,OrgLevel06,OrgLevel06Manager,OrgLevel07ID,OrgLevel07,OrgLevel07Manager,OrgLevel08ID,OrgLevel08,OrgLevel08Manager,OrgLevel09ID,OrgLevel09,OrgLevel09Manager,OrgLevel10ID,OrgLevel10,OrgLevel10Manager,BusinessArea,ProfileArea,Department,ConsolidatedArea,Area,SubArea,CostCenter,Location,Country,Source
Emplid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
93853,806585 VBS I (Filled),297030.0,Filled,2017-08-02,2017-08-02,NaN,Gigi Jones,Michelle Boucher,NaN,0,0,0,2017-08-02,2017-08-02,Shruti (Shruti JAin),Contract Contingent Worker,Contingent Workers,0,Tennessee,24 and under,0,0,NaN,0,0,0,NaN,NaN,NaN,CW001,Contract Service Worker,0.0,SupOrg_00295931,Colonial Life A&H/Life/Cancer Claims,Gigi Jones,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00210462,VB & Colonial Life,Tim Arnold,SupOrg_00202790,Colonial Life & US VB Claims,Deb Rasmussen,SupOrg_00000505,Colonial Life Disability Claims,Christopher Kinback,SupOrg_00295931,Colonial Life A&H/Life/Cancer Claims,Gigi Jones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colonial Life Direct,Colonial Life,CLA Claims,Claims,Claims Ops,Claims Operations,EC6217 CLA Claims Leadership,International,United States of America,NaN
93795,806128 Test Engineer (Filled),209966.0,Filled,2017-06-07,2017-08-14,Jeanette Fulcher,Anne Niles,Sagar Chivate,NaN,0,0,0,2017-07-25,2017-08-14,Sree Aaloori,Hire,External Hires,1,Tennessee,30 - 34,33,1,Female,1,0,0,12T,A21,5.2 Professional - Individual Contributor,IT792-USA,"Test Engineer, US",76000.0,SupOrg_00151825,Administration Journey Tech,Eric Rector,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00208701,Global Services,Christopher Jerome,SupOrg_00219175,Information Technology,Katherine Miller,SupOrg_00217723,UUS: Customer Acquisition and Case Implementation,Oliver McKenna,SupOrg_00151650,CLA: Field Value Stream,Nick Forbes,SupOrg_00151825,Administration Journey Tech,Eric Rector,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Information Technology,Global Servs,Information Technology,Acquisition,Acquisition Svcs,Enrollment CoE,EC0572 Enrollment - US,Chattanooga Home Office,United States of America,Career Section (Inactive)
64879,801278 Client Manager Associate (Filled),285042.0,Filled,2015-01-26,2015-04-06,NaN,Tara Price,Regina Del Campo,NaN,0,0,0,2015-03-02,2015-04-06,Katrina Abad,Change Job,Internal Transfers,1,New York,30 - 34,31,1,Female,1,0,0,50A,NaN,4 Sales,SA483-USA,Client Manager Associate,67600.0,SupOrg_00203601,Unum US Sales & Client Mgmt - East,Regina Del Campo,SupOrg_Executive,Unum Executive,Tom Watjen,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00115378,Unum Group Benefits,Chris Pyne,SupOrg_00104630,UUS Sales and Client Management,John Stibal,SupOrg_00111570,Unum US Sales & Client Mgmt - East,John Spellane,SupOrg_00203601,Unum US Sales & Client Mgmt - East,Regina Del Campo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US Operations,Unum US Growth Ops & Group Benefits,Unum US Sales and Client Management,Field,East,New York,EC2706 New York Sales Office,New York City Sales,United States of America,Internal Job Posting
87237,800719 AVP Global Health and Insurance Program...,284036.0,Filled,2014-10-30,2015-05-11,NaN,Robyn Cash,Rob Hecker,NaN,0,0,0,2015-04-01,2015-05-11,Joanne Abate,Hire,External Hires,1,Maine,50 - 54,54,1,Female,0,0,0,08A,USA,1.4 AVP & Equivalent,HR220-USA,"AVP, Global Health & Insurance Programs",175000.0,SupOrg_00103073,Global HR Benefits,Linda Levesque,SupOrg_Executive,Unum Executive,Tom Watjen,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00305604,People & Communications,Diane Garofalo,SupOrg_00103073,Global HR Benefits,Linda Levesque,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corporate Staff Direct,Corporate HR,Corporate Human Resources,Global Benefits,Benefits,Benefits1,EC9223 Benefits,Portland Home Office,United States of America,Our Employee (Inactive)
95075,806195 Chief Medical Officer (Filled),51323.0,Filled,2017-06-16,2018-02-01,Christopher Schenk (Terminated),Gurveen Chana,Liz Walker,NaN,0,0,0,2017-10-30,2018-02-01,Syed Zakir Abbas,Hire,External Hires,0,Surrey,45 - 49,49,1,Male,1,0,0,16,"UK – Actuarial, MD, Lawyer",1.4 AVP & Equivalent,L103-UK,Chief Medical Officer,150000.0,SupOrg_00293589,Unum UK Customer Services,Steve Harry,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00051934,Unum International,Peter O'Donnell,SupOrg_00293589,Unum UK Customer Services,Steve Harry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unum UK,Unum UK Direct,Unum UK Customer Services,Medical Services,Medical_Services,Medical Svcs,EC7177 Medical Services,Dorking,United Kingdom,Social Network: Linkedin

In [10]:
hire.to_csv(r'O:\people_analytics\scorecards_kpis\ldp\data_build\hire_report_updated.csv')

# RaaS Internal Job Change Details

In [4]:
jch_startdate = '2014-01-01'
jch_enddate = (date.today()).strftime('%Y-%m-%d')

In [5]:
jobchanges = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Internal_Job_Change_Details?SupervisoryOrgFromOrTo%21WID=fad8c8a44c4510541494e34161d00311&BPStatus%21WID=b90bc51be01d4ae99b603b02b073714d&BPType%21WID=e6591cf3a39e44f0b01c711957f72e76!26627c6715f84ddba510f25c433aeb2b!bd774409e883445d8a773a92274ece71!08e574a19f6b400fac5dbe71ea854f1d!367d55bcf1ff49e4afa95b60c8531771!5598cba0054d439690bca4c2a0079eb9!aaa046227982460f98d5a1ca14f91d2b!1758d7cf019a4c6a827fbba824a2866c!c44ef33941cf425f9d4e27e1403c7670&IncludeSubOrgs=1&ChangeEnd={0}-08%3A00&ChangeStart={1}-08%3A00&Organization%21WID=fad8c8a44c4510541494e34161d00311&format=csv'.format(jch_enddate,jch_startdate)
with requests.Session() as s:
    download = s.get(jobchanges, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    jobchanges = pd.read_csv(io.StringIO(decoded_content))
    jobchanges = jobchanges.set_index('Emplid')

C:\Users\DDY17\Anaconda3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (83,84,85) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [6]:
print(jobchanges.shape)
jobchanges.head()

(60026, 134)

,LANID,Worker,Hire,Active,AgeGroup,Age,Diverse,Gender,Minority,Veteran,Disability,HighPotential,RatingStatus,LastRating,PotentialRating,Category,Reason,Type,Effective,Completed,Requisition,ReplacementFor,DaysInJobBeforeChange,DaysInPositionBeforeChange,IsManagerFrom,IsManagerTo,PositionFromID,PositionToID,JobCodeFrom,JobCodeTo,JobProfileFrom,JobProfileTo,JobLevelFrom,JobLevelTo,ManagementLevelFrom,ManagementLevelTo,GradeFrom,GradeTo,BasePayFrom,BasePayTo,StockTargetFrom,StockTargetTo,StockPlanFrom,StockPlanTo,ExemptFrom,ExemptTo,SchedHoursFrom,SchedHoursTo,FullPartTimeFrom,FullPartTimeTo,ManagerFrom,ManagerTo,SupervisoryOrgFromID,SupervisoryOrgFrom,OrgFromManager,OrgFromLevel01ID,OrgFromLevel01,OrgFromLevel01Manager,OrgFromLevel02ID,OrgFromLevel02,OrgFromLevel02Manager,OrgFromLevel03ID,OrgFromLevel03,OrgFromLevel03Manager,OrgFromLevel04ID,OrgFromLevel04,OrgFromLevel04Manager,OrgFromLevel05ID,OrgFromLevel05,OrgFromLevel05Manager,OrgFromLevel06ID,OrgFromLevel06,OrgFromLevel06Manager,OrgFromLevel07ID,OrgFromLevel07,OrgFromLevel07Manager,OrgFromLevel08ID,OrgFromLevel08,OrgFromLevel08Manager,OrgFromLevel09ID,OrgFromLevel09,OrgFromLevel09Manager,OrgFromLevel10ID,OrgFromLevel10,OrgFromLevel10Manager,SupervisoryOrgToID,SupervisoryOrgTo,OrgToManager,OrgToLevel01ID,OrgToLevel01,OrgToLevel01Manager,OrgToLevel02ID,OrgToLevel02,OrgToLevel02Manager,OrgToLevel03ID,OrgToLevel03,OrgToLevel03Manager,OrgToLevel04ID,OrgToLevel04,OrgToLevel04Manager,OrgToLevel05ID,OrgToLevel05,OrgToLevel05Manager,OrgToLevel06ID,OrgToLevel06,OrgToLevel06Manager,OrgToLevel07ID,OrgToLevel07,OrgToLevel07Manager,OrgToLevel08ID,OrgToLevel08,OrgToLevel08Manager,OrgToLevel09ID,OrgToLevel09,OrgToLevel09Manager,OrgToLevel10ID,OrgToLevel10,OrgToLevel10Manager,LocationFrom,LocationTo,BusinessAreaFrom,BusinessAreaTo,ProfileAreaFrom,ProfileAreaTo,DepartmentFrom,DepartmentTo,ConsolidatedAreaFrom,ConsolidatedAreaTo,AreaFrom,AreaTo,SubAreaFrom,SubAreaTo,CostCenterFrom,CostCenterTo
Emplid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
93853,BT417,Shruti (Shruti JAin),2017-08-02,0,24 and under,0,0,NaN,0,0,0,0,No Potential Rating,NaN,NaN,Data Changes,Data Change > Data Changes > Same Job - Change...,Transfer Contingent Worker Inbound,2018-10-04,2018-10-04T09:06:11.265-07:00,NaN,NaN,427,427,0,0,297030.0,305545.0,CW001,CW001,Contract Service Worker,Contract Service Worker,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0,0,40.0,40.0,Full time,Full time,Gigi Jones,Tawana Williams,SupOrg_00295931,Colonial Life A&H/Life/Cancer Claims,Gigi Jones,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00210462,VB & Colonial Life,Tim Arnold,SupOrg_00202790,Colonial Life & US VB Claims,Deb Rasmussen,SupOrg_00000505,Colonial Life Disability Claims,Christopher Kinback,SupOrg_00295931,Colonial Life A&H/Life/Cancer Claims,Gigi Jones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SupOrg_00218724,Superior Organization Colonial Life A&H/Life/C...,Tawana Williams,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00210462,VB & Colonial Life,Tim Arnold,SupOrg_00202790,Colonial Life & US VB Claims,Deb Rasmussen,SupOrg_00000505,Colonial Life Disability Claims,Christopher Kinback,SupOrg_00295931,Colonial Life A&H/Life/Cancer Claims,Gigi Jones,SupOrg_00218724,Superior Organization Colonial Life A&H/Life/C...,Tawana Williams,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,International,International,Colonial Life Direct,Colonial Life Direct,Colonial Life,Colonial Life,CLA Claims,CLA Claims,Claims,Claims,Claims Ops,Claims Ops,Claims Operations,Claims Operations_Other,EC6217 CLA Claims Leadership,EC6115 CLA Claims VBSs
73032,AT412,David A'Hearn,2012-08-06,1,60 and over,62,1,Male,1,0,0,0,No Potential Rating,NaN,NaN,Data Changes,Data Change > Data Changes > Same Job - Change...,Transfer Employee Inbound,2017-04-30,2017-04-30T07:07:52.660-07:00,NaN,NaN,1727,1727,0,0,206804.0,206804.0,CC826-USA,CC826-USA,Financial Benefits Specialist,Financial Benefits Specialist,5.2 Professional - Individual Contributor,5.2 Professional - Individual Contributor,5 Individual Contributor,5 Individual Contributor,12F,12F,50000.0,50000.0,0.0,0.0,NaN,NaN,0,0,40.0,40.0,Full time,Full time,Tara Moore,Robin Evans,SupOrg_00202766,Unum US Benefits Financial Srvc,Tara Moore,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00151199,Unum US Benefits Operations,Greg Breter,SupOrg_00291783,Unum US LTD Regional Benefits Ops - Chattanoog...,Bob Berry,SupOrg_00150670,Unum US Benefits Financial Srvc,John Howard,SupOrg_00202766,Unum US Benefits Financial Srvc,Tara Moore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SupOrg_00296509,Unum US Benefits Financial Srvc,Robin Evans,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00151199,Unum US Benefits Operations,Greg Breter,SupOrg_00291783,Unum US LTD Regional Benefits Ops - Chattanoog...,Bob Berry,SupOrg_00150670,Unum US Benefits Financial Srvc,John Howard,SupOrg_00202766,Unum US Benefits Financial Srvc,Tara Moore,SupOrg_00296509,Unum US Benefits Financial Srvc,Robin Evans,NaN,NaN,NaN,NaN,NaN,NaN,Chattanooga Home Office,Chattanooga Home Office,US Operations,US Operations,Unum US Benefits Center,Unum US Benefits Center,Unum US Benefits Operations,Unum US Benefits Operations,Financial Svcs,Financial Svcs,Financial Services,Financial Services,Chatt Financial Consulting Team,Chatt Financial Consulting Team,EC8113 Financial Consulting Team Chattanooga,EC8113 Financial Consulting Team Chattanooga
73032,AT412,David A'Hearn,2012-08-06,1,60 and over,62,1,Male,1,0,0,0,No Potential Rating,NaN,NaN,Data Changes,Data Change > Data Changes > Same Job - Change...,Transfer Employee Inbound,2017-10-01,2017-09-19T05:49:07.415-07:00,NaN,NaN,1881,1881,0,0,206804.0,206804.0,CC826-USA,CC826-USA,Financial Benefits Specialist,Financial Benefits Specialist,5.2 Professional - Individual Contributor,5.2 Professional - Individual Contributor,5 Individual Contributor,5 Individual Contributor,12F,12F,50000.0,50000.0,0.0,0.0,NaN,NaN,0,0,40.0,40.0,Full time,Full time,Robin Evans,Chris Foster,SupOrg_00296509,Unum US Benefits Financial Srvc,Robin Evans,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00151199,Unum US Benefits Operations,Greg Breter,SupOrg_00291783,Unum US LTD Regional Benefits Ops - Chattanoog...,Bob Berry,SupOrg_00150670,Unum US Benefits Financial Srvc,John Howard,SupOrg_00296509,Unum US Benefits Financial Srvc,Robin Evans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SupOrg_00296761,Unum US Benefits Shared Financial Srvc,Chris Foster,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00151199,Unum US Benefits Operations,Greg Breter,SupOrg_00291783,Unum US LTD Regional Benefits Ops - Chattanoog...,Bob Berry,SupOrg_00150670,Unum US Benefits Financial Srvc,John Howard,SupOrg_00296509,Unum US Benefits Financial Srvc,Robin Evans,SupOrg_00296761,Unum US Benefits Shared Financial Srvc,Chris Foster,NaN,NaN,NaN,NaN,NaN,NaN,Chattanooga Home Office,Chattanooga Home Office,US Operations,US Operations,Unum US Benefits Center,Unum US Benefits Center,Unum US Benefits Operations,Unum US Benefits Operations,Financial Svcs,Financial Svcs,Financial Services,Financial Services,Portland Financial Consulting Team,Portland Financial Consulting Team,EC8758 Financial Consulting Team - LTD,EC8758 Financial Consulting Team - LTD
73032,AT412,David A'Hearn,2012-08-06,1,60 and over,64,1,Male,1,0,0,0,No Potential Rating,NaN,NaN,Data Changes,Data Change > Data Changes > Same Job - Change...,Transfer Employee Inbound,2019-08-11,2019-08-02T06:26:34.570-07:00,NaN,NaN,2560,2560,0,0,206804.0,206804.0,CC826-USA,CC826-USA,Financial Benefits Specialist,Financial Benefits Specialist,5.2 Professional - Individual Contributor,5.2 Professional - Individual Contributor,5 Individual Contributor,5 Individual Contributor,9,9,51765.0,51765.0,0.0,0.0,NaN,NaN,0,0,40.0,40.0,Full time,Full time,Chris Foster,Kathy Maloney,SupOrg_00296761,Unum US Benefits Shared Financial Srvc,Chris Foster,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00151199,Unum US Benefits Operations,Greg Breter,SupOrg_00216660,Unum US Benefits Operations,Lori Whynot,SupOrg_00100871,"Unum US Benefits Financial Srvc, LTD Regional ...",Joy Michaud,SupOrg_00150670,Unum US Benefits Financial Srvc,John Howard,SupOrg_00296509,Unum US Benefits Financial Srvc,Robin Evans,SupOrg_00296761,Unum US Benefits Shared Financial Srvc,Chris Foster,NaN,NaN,NaN,SupOrg_00209704,Unum US Benefits Financial Srvc,Kathy Maloney,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00151199,Unum US Benefits Operations,Greg Breter,SupOrg_00216660,Unum US Benefits Operations,Lori Whynot,SupOrg_00100871,"Unum US Benefits Financial Srvc, LTD Regional ...",Joy Michaud,SupOrg_00150670,Unum US Benefits Financial Srvc,John Howard,SupOrg_00104950,Unum US Benefits Financial Srvc,Tamra Bevilacqua,SupOrg_00209704,Unum US Benefits Financial Srvc,Kathy Maloney,NaN,NaN,NaN,Chattanooga Home Office,Chattanooga Home Office,US Operations,US Operations,Unum US Benefits Center,Unum US Benefits Center,Unum US Benefits Operations,Unum US Benefits Operations,Financial Svcs,Financial Svcs,Financial Services,Financial Services,Financial Consulting Teams,Financial Consulting Teams,EC8758 Financial Consulting Team - LTD,EC8758 Financial Consulting Team - LTD
93795,BR417,Sree Aaloori,2017-08-14,1,30 - 34,33,1,Female,1,0,0,0,No Potential Rating,NaN,NaN,NaN,NaN,Hire,2017-08-14,2017-07-25T13:46:27.419-07:00,806128 Test Engineer (Filled),Jeanette Fulcher,0,0,0,0,NaN,209966.0,NaN,IT792-USA,NaN,"Test Engineer, US",NaN,5.2 Professional - Individual Contributor,NaN,5 Individual Contributor,NaN,12T,0.0,76000.0,0.0,0.0,NaN,NaN,0,1,0.0,40.0,NaN,Full time,NaN,Eric Rector,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SupOrg_00151825,Administration Journey Tech,Eric Rector,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00208701,Global Services,Christopher Jerome,SupOrg_00219175,Information Technology,Katherine Miller,SupOrg_00217723,UUS: Customer Acquisition and Case Implementation,Oliver McKenna,SupOrg_00151650,CLA: Field Value Stream,Nick Forbes,SupOrg_00151825,Administration Journey Tech,Eric Rector,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chattanooga Home Office,NaN,Information Technology,NaN,Global Servs,NaN,Information Technology,NaN,Acquisition,NaN,Acquisition Svcs,NaN,Enrollment CoE,NaN,EC0572 Enrollment - US

In [6]:
jobchanges = jobchanges.rename(columns={'Job_Change_Date':'Job Change Date',
 'Job_Change_Reason':'Job Change Reason',
 'Job_Change_Type':'Job Change Type',
 'Years_in_Job_Profile_Before_Change':'Years in Job Profile Before Change',
 'Time_in_Job_Profile_Before_Change':'Time in Job Profile Before Change',
 'Time_in_Position_Before_Change':'Time in Position Before Change',
 'Job_Code_-_From':'Job Code - From',
 'Job_Code_-_To':'Job Code - To',
 'Job_Profile_-_From':'Job Profile - From',
 'Job_Profile_-_To':'Job Profile - To',
 'Grade_-_From': 'Grade - From',
 'Grade_-_To':'Grade - To',
 'Job_Level_From':'Job Level From',
 'Job_Level_To':'Job Level To',
 'Is_Manager_From':'Is Manager - From',
 'Is_Manager_To':'Is Manager - To',                                        
 'Base_Pay_-_From':'Base Pay - From',
 'Base_Pay_-_To':'Base Pay - To',
 'Sched_Hours_-_From':'Sched Hours - From',
 'Sched_Hours_-_To':'Sched Hours - To',
 'Manager_-_From':'Manager - From',
 'Manager_-_To':'Manager - To',
 'Supervisory_Org_-_From':'Supervisory Org - From',
 'Supervisory_Org_-_To':'Supervisory Org - To',
 'Location_-_From':'Location - From',
 'Location_-_To':'Location - To',
 'Cost_Center_-_From':'Cost Center - From',
 'Cost_Center_-_To':'Cost Center - To',
 'Business_Area_-_From':'Business Area - From',
 'Business_Area_-_To':'Business Area - To',
 'Profile_Area_-_From':'Profile Area - From',
 'Profile_Area_-_To':'Profile Area - To',
 'Department_-_From':'Department - From',
 'Department_-_To':'Department - To',
 'Consolidated_Area_-_From':'Consolidated Area - From',
 'Consolidated_Area_-_To':'Consolidated Area - To',
 'Area_-_To':'Area - To',
 'Sub_Area_-_To':'Sub Area - To',
 'Potential_Rating':'Potential Rating',
 'Rating_Status':'Rating Status',
 'Last_Rating':'Last Rating'})

In [7]:
#jobchanges.to_csv(r'O:\people_analytics\scorecards_kpis\ldp\data_build\internal_job_changes_update.csv')
jobchanges.to_csv(r'C:\Users\DDY17\OneDrive - Unum\R Files\job_changes_2017_now.csv')

# RaaS Terminated Worker Details (2014+)

In [13]:
termstart = '2000-01-01'
termend = (date.today()).strftime('%Y-%m-%d')

In [14]:
terminations = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Terminated_Worker_Details__2014__?Term_Start_Date={0}-08%3A00&Term_End_Date={1}-08%3A00&Supervisory_Organization%21WID=fad8c8a44c4510541494e34161d00311&Employee_Type%21WID=c4ed1a5d88a41050a1f47a5de48823db!c4ed1a5d88a41050a1f47c52de8823dc&format=csv'.format(termstart,termend)
with requests.Session() as s:
    download = s.get(terminations, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    terminations = pd.read_csv(io.StringIO(decoded_content))
    terminations = terminations.set_index('Employee_ID')

In [15]:
print(terminations.shape)
terminations.head()

(10337, 52)

,LANID,Name,primaryWorkEmail,Most_Recent_Hire_Date,Original_Hire_Date,Most_Recent_Term_Date,Is_Term_90_Day_Hire,Term_Reason,Secondary_Term_Reason,Term_Category,Employee_has_had_Performance_Improvement_or_Reprimand_Plan,Eligible_for_Rehire,Job_Profile,Time_in_Job_Profile,Time_in_Job_Profile__Partial_Years_,Job_Code,Job_Level,Grade,Annual_Salary,Worker_Type,Time_Type,Employee_Type,Scheduled_Hours,Exempt_,Job_Exempt_Applies,Job_Family,Job_Family_Group,Manager,Leadership_Role,location,Campus,Supervisory_Organization,Tenure_Category_-_Position,Years_of_Service,Years_in_Current_Position,Time_in_Job_Profile_Start_Date,Gender,Race_Ethnicity,Hispanic_or_Latino,Disability,Veteran,Age_Group,Age,Cost_Center,Email_-_Primary_Home,Term_Location_Country,Profile_Area_Division,Department,Consolidated_Area,Area,Sub-Area,Potential_-_Completed_Rating
Employee_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
95075,D1P17,Syed Zakir Abbas,SyedZakir.Abbas@unum.co.uk,2018-02-01,2018-02-01,2020-12-30,N,No Placement,NaN,Job Elimination/Redundancy,0,NaN,Chief Medical Officer,"2 year(s), 10 month(s), 29 day(s)",2.91,L103-UK,1.3 VP & Equivalent,16,151500.0,Employee,Part time,Regular,29.00,0,0,Doctors,NaN,Liz Walker,1 Senior Leader,Dorking,Dorking,Unum UK Customer Services (Liz Walker),02 - 05 Years,2.91,2.91,2018-02-01,Male,Pakistani (United Kingdom),NaN,0,Veteran Status = No,50 - 54,52,EC7177 Medical Services,zakirabbas@doctors.org.uk,United Kingdom,Unum UK Direct,Unum UK Customer Services,Customer Care Services,Customer Care Srvs,Claims_Subarea,Well Placed
12440,ASH10,Ann-Marie Abbott,AAbbott3@UNUM.COM,2011-07-01,1985-06-17,2015-06-30,N,LTD - 6 Months,NaN,Other,0,NaN,Sr. Staffing Consultant,"3 year(s), 11 month(s), 29 day(s)",4.00,HR508-USA,3 Managers,11E,81143.0,Employee,Full time,Regular,40.00,1,1,All Other,Other Job Families,Marcia Leander,4 Senior Individual Contributor,Portland Home Office,Portland,Executive Recruiting and TA Operations (Marcia...,02 - 05 Years,4.00,4.00,2011-07-01,Female,White (United States of America),0.0,0,Veteran Status = No,55 - 59,58,EC0311 Executive Talent Acquisition,placeholder@email.com,United States of America,Corporate HR,Corporate Human Resources,Global Talent Acquisition,Active EE-Global Talent Mgt Corp,Staffing/Recruiting1 Progs,NaN
96931,BG218,Brandon Abbott,BAbbott@ColonialLife.com,2018-06-11,2018-06-11,2018-08-31,Y,Personal,NaN,Voluntary,0,NaN,Manager III,"0 year(s), 2 month(s), 20 day(s)",0.22,CS512-USA,3 Managers,13,75000.0,Employee,Full time,Regular,40.00,1,1,Customer Services,NaN,Kevin Pillsbury,3 Management,Colonial Life Home Office,Columbia,US Service Operations (Kevin Pillsbury),00 - 01 Years,0.22,0.22,2018-06-11,Male,White (United States of America),0.0,0,Veteran Status = No,30 - 34,34,EC6172 Account Services Admin,abbottbn@hotmail.com,United States of America,Colonial Life,CLA Customer Operations,CLA Account Services,AS Leadership,CLA_Leadership,NaN
99121,D7I18,Michael Abbott,MAbbott2@UNUM.COM,2018-12-03,2018-12-03,2020-01-20,N,Other Position,NaN,Voluntary,0,No,"Dir, Policies & Procedures","1 year(s), 1 month(s), 17 day(s)",1.13,UW459-USA,2 Directors,14,110000.0,Employee,Full time,Regular,40.00,1,1,Operational Support,NaN,Jennifer Robare,3 Management,Worcester Home Office,Worcester,"Unum US IDI Policy & Practice, Training & QR (...",01 - 02 Years,1.13,1.13,2018-12-03,Male,White (United States of America),0.0,0,Veteran Status = No,50 - 54,50,EC8358 IDI P&P and QA,mabbo1105@comcast.net,United States of America,Unum Specialty Business,Unum US_IDI Business Operations,IDI Business Operations,IDI Shared Services,IDI Employee Experience,Well Placed
71693,NaN,Shenaid Abbs,unum@unum.com,2011-09-19,2011-09-19,2014-03-28,N,Personal,NaN,Voluntary,0,NaN,Snr Customer Fdbk Specialist,"0 year(s), 6 month(s), 26 day(s)",0.57,UA001-UK,5.2 Professional - Individual Contributor,4UA,23200.0,Employee,Full time,Regular,36.25,0,0,All Other,Other Job Families,Peter Goddard,5 Individual Contributor,Dorking,NaN,UK Legal & Compliance (Peter Goddard),02 - 05 Years,2.52,0.57,2013-09-02,Female,White (United Kingdom) (inactive),NaN,0,Veteran Status = No,24 and under,24,EC7021 Insurance Compliance,placeholder@email.com,United Kingdom,Unum UK Direct,Unum UK Risk and Governance,Corporate - Services,Corporate__Services,Compliance_Subarea,NaN

In [22]:
terminations = terminations.rename(columns={'Employee_ID':'Employee ID',
  'primaryWorkEmail':'Email - Primary Work',
 'Hire_Date':'Hire Date',
 'Term_Date':'Term Date',
 'Terminated__based_on_report_date_':'Terminated Based on Report Date',
 'CF_Worker_Latest_Term_Date':'CF Worker Lastest Term Date',
 'Is_Term_90_Day_Hire':'Is Term 90 Day Hire',
 'Term_Reason':"Term Reason",
 'termination_primary':'Termination Primary',
 'Secondary_Term_Reason':'Secondary Term Reason',
 'Term_Category':'Term Category',
 'Employee_has_had_Performance_Improvement_or_Reprimand_Plan':'Employee had has Performance Improvement or Reprimand Plan',
 'Eligible_for_Rehire':'Eligible for Rehire',
 'Job_Profile':'Job Profile',
 'Time_in_Job_Profile':'Time in Job Profile',
 'Job_Code':'Job Code',
 'Job_Level':'Job Level',
 'Annual_Salary':'Annual Salary',
 'Worker_Type':'Worker Type',
 'Time_Type':'Time Type',
 'Employee_Type':'Employee Type',
 'Scheduled_Hours':'Scheduled Hours',
 'Exempt_':'Exempt',
 'Job_Exempt_Applies':'Job Exempt Applies',
 'Job_Family':'Job Family',
 'Job_Family_Group':'Job Family Group',
 'Leadership_Role':'Leadership Role',
 'location':'Location',
 'Supervisory_Organization':'Supervisory Organization',
 'Tenure_Category_-_Position':'Tenure Category - Position',
 'Years_of_Service':'Years of Service',
 'Race_Ethnicity':'Race Ethnicity',
 'Hispanic_or_Latino':'Hispanic or Latino',
 'Age_Group':'Age Group',
 'Cost_Center':'Cost Center',
 'Email_-_Work':'Email - Work',
 'Profile_Area_Division':'Profile Area Division',
 'Consolidated_Area':'Consolidated Area',
 'Potential_-_Completed_Rating':'Potential - Completed Rating',
 'Last_Update_-_Potential':'Last Update - Potential',
 'effectiveDate':'Effective Date',
 'staffingPlanTitle':'Staffing Plan Title',
 'fieldOfficeProfileIndicator':'Field Office Profile Indicator'})

In [16]:
terminations.to_csv(r'O:\people_analytics\scorecards_kpis\ldp\data_build\term_worker_details.csv')

# RaaS Candidate Data

### ADP/AFDP Candidate Data

In [11]:
adp_afdp_candidates = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Candidate_Data?Internal=0&Job_Profile%21WID=2a18aa346de810528f0098df37904f81!2a18aa346de810528f00a35f6b404f8d!2a18aa346de810528f00a72729704f91!a9ad2a8b8c5301f3e4df754e01507b93&format=csv'
with requests.Session() as s:
    download = s.get(adp_afdp_candidates, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    adp_afdp_candidates = pd.read_csv(io.StringIO(decoded_content))
    adp_afdp_candidates = adp_afdp_candidates.set_index('Candidate')

In [12]:
print(adp_afdp_candidates.shape)
adp_afdp_candidates.head()

(6178, 46)

,Candidate_ID,Stage,Status,Last_Recruiting_Stage,Disposition_Reason,Candidate_Disposition_Reason,Internal_,App_Created,Employee_ID,termination_date,Hire_Date,JKCF_-_Format_App_Created_Date__MM-YYYY_,Do_Not_Hire,Step,CF_Calc_Candidate_Stage,App_Source,Diversity,Minority,Gender,Veteran,Disability,Recruiter,Recruiter_s_Department,Department,CF_Job_Requisition_Business_Area_SI,INT0027_Job_Requisition_Exempt,LDCF_EE_SLC_Member,Requisition,CF_LRV_Job_Req_ID_from_Job_Req,Req_Location,Hiring_Mgr,Job_Profile,Compensation_Grade,Job_Level,Employee_Type,Req_Created,CF_Job_App_Req_Cmplt_Date,CF_Job_App_Offer_Cmplt_Date,JKCF_-_Job_Offer_Complete_Date__Format_Y-Q_,JKCF_-_Return_1_for_In_Thru_Review_Stage,JKCF_-_Return_1_for_In_Thru_Assessment_Stage,JKCF_-_Return_1_for_In_Thru_Screen_Stage,JKCF_-_Return_1_for_In_Thru_Interview_Stage,JKCF_-_Return_1_for_In_Thru_Offer_Stage,JKCF_-_Return_1_for_In_Thru_Background_Check_Stage,JKCF_-_Return_1_for_In_Thru_Ready_for_Hire_Stage
Candidate,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Kyle Choate,C10389,Ready for Hire,Hired,Ready for Hire,NaN,NaN,0,2017-10-23,96716.0,NaN,2018-06-04,Q4-2017,0,Completion,Ready for Hire,Job Board -> Indeed (inactive),Non-Diverse,Non-Minority,Male,0,0,NaN,NaN,Finance,Corporate Staff Direct,1,Liz Ahmed,806687 Actuarial Assistant (Filled),806687,Chattanooga Home Office,Emily Kauchak,Actuarial Assistant,10,5.2 Professional - Individual Contributor,External,2017-08-15,2017-08-16,2018-04-10T14:21:42.160-07:00,2018-Q2,1,1,1,1,1,1,1
Aaron Gulibon,C31496,Rejected,No longer under consideration,Screen,Candidate did not respond,NaN,0,2018-01-31,NaN,NaN,NaN,Q1-2018,0,NaN,Screen,College/University Website or Event -> Univers...,Non-Diverse,Non-Minority,Male,0,0,NaN,NaN,Finance,Corporate Staff Direct,1,Liz Ahmed,806732 Finance Development Program Associate (...,806732,Chattanooga Home Office,Emily Kauchak,Finance Development Program Assoc,12,3 Managers,External,2017-08-18,2017-08-21,NaN,NaN,1,1,1,0,0,0,0
Aaron Rosauer,C32130,Rejected,No longer under consideration,Screen,Position is filled,NaN,0,2018-02-03,NaN,NaN,NaN,Q1-2018,0,NaN,Screen,Job Board -> Indeed - Sponsored (inactive),Non-Diverse,Non-Minority,Male,0,0,NaN,NaN,Finance,Corporate Staff Direct,1,Liz Ahmed,806732 Finance Development Program Associate (...,806732,Chattanooga Home Office,Emily Kauchak,Finance Development Program Assoc,12,3 Managers,External,2017-08-18,2017-08-21,NaN,NaN,1,1,1,0,0,0,0
ABBEY ZHENG,C39516,Rejected,No longer under consideration,Review,Requires employment sponsorship (now or in the...,NaN,0,2018-03-07,NaN,NaN,NaN,Q1-2018,0,NaN,Review,Professional Organization -> All Professional ...,Diverse,Minority,Female,0,0,NaN,NaN,Finance,Corporate Staff Direct,1,Liz Ahmed,806732 Finance Development Program Associate (...,806732,Chattanooga Home Office,Emily Kauchak,Finance Development Program Assoc,12,3 Managers,External,2017-08-18,2017-08-21,NaN,NaN,1,0,0,0,0,0,0
Adnan Naufaldi,C22299,Rejected,No longer under consideration,Administrative,Candidate did not respond,NaN,0,2017-12-19,NaN,NaN,NaN,Q4-2017,0,NaN,Administrative,Company Web Site -> Company Career Site,Diverse,Minority,Male,0,0,NaN,NaN,Finance,Corporate Staff Direct,1,Liz Ahmed,806732 Finance Development Program Associate (...,806732,Chattanooga Home Office,Emily Kauchak,Finance Development Program Assoc,12,3 Managers,External,2017-08-18,2017-08-21,NaN,NaN,0,0,0,0,0,0,0

In [13]:
adp_afdp_candidates = adp_afdp_candidates.rename(columns={'Candidate_ID':'Candidate ID',
 'Last_Recruiting_Stage':'Last Recruiting Stage',
 'Disposition_Reason':'Disposition Reason',
 'Candidate_Disposition_Reason':'Candidate Disposition Reason',
 'Internal_':'Internal',
 'App_Created':'App Created',
 'Employee_ID':'Employee ID',
 'termination_date':'Termination Date',
 'Hire_Date':'Hire Date',
 'JKCF_-_Format_App_Created_Date__MM-YYYY_':'App Created (Quarter-Year)',
 'Do_Not_Hire':'Do Not Hire',
 'CF_Calc_Candidate_Stage':'CF Calc Candidate Stage',
 'App_Source':'App Source',
 'Recruiter_s_Department':'Recruiters Department',
 'CF_Job_Requisition_Business_Area_SI':'Business Area',
 'LDCF_EE_SLC_Member':'SLC Member',
 'Req_Location':'Req Location',
 'Hiring_Mgr':'Hiring Mgr',
 'Job_Profile':'Job Profile',
 'Compensation_Grade':'Compensation Grade',
 'Job_Level':'Job Level',
 'Req_Created':'Req Created',
 'CF_Job_App_Req_Cmplt_Date':'App Created',
 'CF_Job_App_Offer_Cmplt_Date':'Offer Completed',
 'JKCF_-_Job_Offer_Complete_Date__Format_Y-Q_':'Offer Completed (Y-Q)',
 'JKCF_-_Return_1_for_In_Thru_Review_Stage':'In/Thru Review',
 'JKCF_-_Return_1_for_In_Thru_Assessment_Stage':'In/Thru Assessment',
 'JKCF_-_Return_1_for_In_Thru_Screen_Stage':'In/Thru Screen',
 'JKCF_-_Return_1_for_In_Thru_Interview_Stage':'In/Thru Interview',
 'JKCF_-_Return_1_for_In_Thru_Offer_Stage':'In/Thru Offer',
 'JKCF_-_Return_1_for_In_Thru_Background_Check_Stage':'In/Thru Background Check',
 'JKCF_-_Return_1_for_In_Thru_Ready_for_Hire_Stage':'In/Thru Ready for Hire'})

In [14]:
adp_afdp_candidates.to_csv(r'O:\people_analytics\scorecards_kpis\ldp\data_build\adp_afdp_candidates_export.csv')

### PDP Candidate Data

In [23]:
pdp_candidates = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Candidate_Data?Internal=0&JKCF_-_LRV_Primary_Recruiter_s_Department%21WID=1dd9ce98a6940104889a0b5381d7f3f1&Job_Profile%21WID=2a18aa346de810528f404b23be287596&format=csv'
with requests.Session() as s:
    download = s.get(pdp_candidates, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    pdp_candidates = pd.read_csv(io.StringIO(decoded_content))
    pdp_candidates = pdp_candidates.set_index('Candidate')

In [24]:
print(pdp_candidates.shape)
pdp_candidates.head()

(2463, 46)

,Candidate_ID,Stage,Status,Last_Recruiting_Stage,Disposition_Reason,Candidate_Disposition_Reason,Internal_,App_Created,Employee_ID,termination_date,Hire_Date,JKCF_-_Format_App_Created_Date__MM-YYYY_,Do_Not_Hire,Step,CF_Calc_Candidate_Stage,App_Source,Diversity,Minority,Gender,Veteran,Disability,Recruiter,Recruiter_s_Department,Department,CF_Job_Requisition_Business_Area_SI,INT0027_Job_Requisition_Exempt,LDCF_EE_SLC_Member,Requisition,CF_LRV_Job_Req_ID_from_Job_Req,Req_Location,Hiring_Mgr,Job_Profile,Compensation_Grade,Job_Level,Employee_Type,Req_Created,CF_Job_App_Req_Cmplt_Date,CF_Job_App_Offer_Cmplt_Date,JKCF_-_Job_Offer_Complete_Date__Format_Y-Q_,JKCF_-_Return_1_for_In_Thru_Review_Stage,JKCF_-_Return_1_for_In_Thru_Assessment_Stage,JKCF_-_Return_1_for_In_Thru_Screen_Stage,JKCF_-_Return_1_for_In_Thru_Interview_Stage,JKCF_-_Return_1_for_In_Thru_Offer_Stage,JKCF_-_Return_1_for_In_Thru_Background_Check_Stage,JKCF_-_Return_1_for_In_Thru_Ready_for_Hire_Stage
Candidate,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Aaliyah Boney,C61918,Rejected,No longer under consideration,Review,Stronger candidate available,NaN,0,2018-06-17,NaN,NaN,NaN,Q2-2018,0,NaN,Review,Company Web Site -> Company Career Site,Diverse,Minority,Female,1,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,809386 Professional Development Program Associ...,809386,Portland Home Office,Hanako Cashin,Prof Development Program Assoc,12,3 Managers,External,2018-05-17,2018-05-17,NaN,NaN,1,0,0,0,0,0,0
Aaron Bertolucci,C91172,Rejected,No longer under consideration,Review,Does not meet the required criteria for the role,NaN,0,2018-10-07,NaN,NaN,NaN,Q4-2018,0,NaN,Review,Social Network -> Social Network: Glassdoor,Non-Diverse,Non-Minority,Male,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,809386 Professional Development Program Associ...,809386,Portland Home Office,Hanako Cashin,Prof Development Program Assoc,12,3 Managers,External,2018-05-17,2018-05-17,NaN,NaN,1,0,0,0,0,0,0
Aaron Johnson,C52864,Rejected,No longer under consideration,Review,Does not meet the required criteria for the role,NaN,0,2018-05-29,NaN,NaN,NaN,Q2-2018,0,NaN,Review,Social Network -> Social Network: Glassdoor,Diverse,Minority,Male,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,809386 Professional Development Program Associ...,809386,Portland Home Office,Hanako Cashin,Prof Development Program Assoc,12,3 Managers,External,2018-05-17,2018-05-17,NaN,NaN,1,0,0,0,0,0,0
Aaron Wright,C57059,Rejected,No longer under consideration,Screen,Stronger candidate available,NaN,0,2018-05-23,NaN,NaN,NaN,Q2-2018,0,NaN,Screen,Referral -> Employee Referral,Diverse,Minority,Male,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,809386 Professional Development Program Associ...,809386,Portland Home Office,Hanako Cashin,Prof Development Program Assoc,12,3 Managers,Referral External,2018-05-17,2018-05-17,NaN,NaN,1,1,1,0,0,0,0
Abdulkhalim Baymatov,C93124,Rejected,No longer under consideration,Review,Does not meet the required criteria for the role,NaN,0,2018-10-14,NaN,NaN,NaN,Q4-2018,0,NaN,Review,College/University Website or Event -> Univers...,Non-Diverse,Non-Minority,NaN,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,809386 Professional Development Program Associ...,809386,Portland Home Office,Hanako Cashin,Prof Development Program Assoc,12,3 Managers,External,2018-05-17,2018-05-17,NaN,NaN,1,0,0,0,0,0,0

In [25]:
pdp_candidates = pdp_candidates.rename(columns={'Candidate_ID':'Candidate ID',
 'Last_Recruiting_Stage':'Last Recruiting Stage',
 'Disposition_Reason':'Disposition Reason',
 'Candidate_Disposition_Reason':'Candidate Disposition Reason',
 'Internal_':'Internal',
 'App_Created':'App Created',
 'Employee_ID':'Employee ID',
 'termination_date':'Termination Date',
 'Hire_Date':'Hire Date',
 'JKCF_-_Format_App_Created_Date__MM-YYYY_':'App Created (Quarter-Year)',
 'Do_Not_Hire':'Do Not Hire',
 'CF_Calc_Candidate_Stage':'CF Calc Candidate Stage',
 'App_Source':'App Source',
 'Recruiter_s_Department':'Recruiters Department',
 'CF_Job_Requisition_Business_Area_SI':'Business Area',
 'LDCF_EE_SLC_Member':'SLC Member',
 'Req_Location':'Req Location',
 'Hiring_Mgr':'Hiring Mgr',
 'Job_Profile':'Job Profile',
 'Compensation_Grade':'Compensation Grade',
 'Job_Level':'Job Level',
 'Req_Created':'Req Created',
 'CF_Job_App_Req_Cmplt_Date':'App Created',
 'CF_Job_App_Offer_Cmplt_Date':'Offer Completed',
 'JKCF_-_Job_Offer_Complete_Date__Format_Y-Q_':'Offer Completed (Y-Q)',
 'JKCF_-_Return_1_for_In_Thru_Review_Stage':'In/Thru Review',
 'JKCF_-_Return_1_for_In_Thru_Assessment_Stage':'In/Thru Assessment',
 'JKCF_-_Return_1_for_In_Thru_Screen_Stage':'In/Thru Screen',
 'JKCF_-_Return_1_for_In_Thru_Interview_Stage':'In/Thru Interview',
 'JKCF_-_Return_1_for_In_Thru_Offer_Stage':'In/Thru Offer',
 'JKCF_-_Return_1_for_In_Thru_Background_Check_Stage':'In/Thru Background Check',
 'JKCF_-_Return_1_for_In_Thru_Ready_for_Hire_Stage':'In/Thru Ready for Hire'})

In [26]:
pdp_candidates.to_csv(r'O:\people_analytics\scorecards_kpis\ldp\data_build\pdp_candidates_export.csv')

### ALP Candidate Data

In [15]:
alp_candidates = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Candidate_Data?Internal=0&Job_Profile%21WID=a04c256469720175e4e817c392839858&format=csv'
with requests.Session() as s:
    download = s.get(alp_candidates, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    alp_candidates = pd.read_csv(io.StringIO(decoded_content))
    alp_candidates = alp_candidates.set_index('Candidate')

In [16]:
print(alp_candidates.shape)
alp_candidates.head()

(349, 46)

,Candidate_ID,Stage,Status,Last_Recruiting_Stage,Disposition_Reason,Candidate_Disposition_Reason,Internal_,App_Created,Employee_ID,termination_date,Hire_Date,JKCF_-_Format_App_Created_Date__MM-YYYY_,Do_Not_Hire,Step,CF_Calc_Candidate_Stage,App_Source,Diversity,Minority,Gender,Veteran,Disability,Recruiter,Recruiter_s_Department,Department,CF_Job_Requisition_Business_Area_SI,INT0027_Job_Requisition_Exempt,LDCF_EE_SLC_Member,Requisition,CF_LRV_Job_Req_ID_from_Job_Req,Req_Location,Hiring_Mgr,Job_Profile,Compensation_Grade,Job_Level,Employee_Type,Req_Created,CF_Job_App_Req_Cmplt_Date,CF_Job_App_Offer_Cmplt_Date,JKCF_-_Job_Offer_Complete_Date__Format_Y-Q_,JKCF_-_Return_1_for_In_Thru_Review_Stage,JKCF_-_Return_1_for_In_Thru_Assessment_Stage,JKCF_-_Return_1_for_In_Thru_Screen_Stage,JKCF_-_Return_1_for_In_Thru_Interview_Stage,JKCF_-_Return_1_for_In_Thru_Offer_Stage,JKCF_-_Return_1_for_In_Thru_Background_Check_Stage,JKCF_-_Return_1_for_In_Thru_Ready_for_Hire_Stage
Candidate,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Aaron Rowan,C17818,Interview,Evaluation in progress,Interview,NaN,NaN,1,2020-02-14,87825.0,NaN,2015-06-22,Q1-2020,0,Onsite Interview,Interview,Job Board -> Internal Job Posting,Non-Diverse,Non-Minority,Male,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,815450 Accelerated Leadership Program (ALP) (E...,815450,Portland Home Office,Kim Bolton,Accelerated Leadership Program,NaN,NaN,Internal,2020-01-29,2020-01-29,NaN,NaN,1,1,1,1,0,0,0
Abby Tolar,C171681,Interview,Evaluation in progress,Interview,NaN,NaN,1,2020-02-12,89951.0,2016-07-21,2017-06-05,Q1-2020,0,Onsite Interview,Interview,Job Board -> Internal Job Posting,Diverse,Non-Minority,Female,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,815450 Accelerated Leadership Program (ALP) (E...,815450,Portland Home Office,Kim Bolton,Accelerated Leadership Program,NaN,NaN,Internal,2020-01-29,2020-01-29,NaN,NaN,1,1,1,1,0,0,0
Alex Torpey,C22900,Rejected,No longer under consideration,Screen,Stronger candidate available,NaN,1,2020-02-14,73276.0,NaN,2012-10-01,Q1-2020,0,NaN,Screen,Job Board -> Internal Job Posting,Diverse,Non-Minority,Female,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,815450 Accelerated Leadership Program (ALP) (E...,815450,Portland Home Office,Kim Bolton,Accelerated Leadership Program,NaN,NaN,Internal,2020-01-29,2020-01-29,NaN,NaN,1,1,1,0,0,0,0
Amanda Jimino,C126259,Interview,Evaluation in progress,Interview,NaN,NaN,1,2020-02-14,64569.0,NaN,2007-10-08,Q1-2020,0,Onsite Interview,Interview,Job Board -> Internal Job Posting,Diverse,Non-Minority,Female,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,815450 Accelerated Leadership Program (ALP) (E...,815450,Portland Home Office,Kim Bolton,Accelerated Leadership Program,NaN,NaN,Internal,2020-01-29,2020-01-29,NaN,NaN,1,1,1,1,0,0,0
Amanda Raffety,C2053,Interview,Evaluation in progress,Interview,NaN,NaN,1,2020-02-07,95153.0,NaN,2017-12-11,Q1-2020,0,Onsite Interview,Interview,Job Board -> Internal Job Posting,Diverse,Non-Minority,Female,0,0,Allie Platts,People and Communications,People and Communications,Corporate Staff Direct,1,Liz Ahmed,815450 Accelerated Leadership Program (ALP) (E...,815450,Portland Home Office,Kim Bolton,Accelerated Leadership Program,NaN,NaN,Internal,2020-01-29,2020-01-29,NaN,NaN,1,1,1,1,0,0,0

In [17]:
alp_candidates = alp_candidates.rename(columns={'Candidate_ID':'Candidate ID',
 'Last_Recruiting_Stage':'Last Recruiting Stage',
 'Disposition_Reason':'Disposition Reason',
 'Candidate_Disposition_Reason':'Candidate Disposition Reason',
 'Internal_':'Internal',
 'App_Created':'App Created',
 'Employee_ID':'Employee ID',
 'termination_date':'Termination Date',
 'Hire_Date':'Hire Date',
 'JKCF_-_Format_App_Created_Date__MM-YYYY_':'App Created (Quarter-Year)',
 'Do_Not_Hire':'Do Not Hire',
 'CF_Calc_Candidate_Stage':'CF Calc Candidate Stage',
 'App_Source':'App Source',
 'Recruiter_s_Department':'Recruiters Department',
 'CF_Job_Requisition_Business_Area_SI':'Business Area',
 'LDCF_EE_SLC_Member':'SLC Member',
 'Req_Location':'Req Location',
 'Hiring_Mgr':'Hiring Mgr',
 'Job_Profile':'Job Profile',
 'Compensation_Grade':'Compensation Grade',
 'Job_Level':'Job Level',
 'Req_Created':'Req Created',
 'CF_Job_App_Req_Cmplt_Date':'App Created',
 'CF_Job_App_Offer_Cmplt_Date':'Offer Completed',
 'JKCF_-_Job_Offer_Complete_Date__Format_Y-Q_':'Offer Completed (Y-Q)',
 'JKCF_-_Return_1_for_In_Thru_Review_Stage':'In/Thru Review',
 'JKCF_-_Return_1_for_In_Thru_Assessment_Stage':'In/Thru Assessment',
 'JKCF_-_Return_1_for_In_Thru_Screen_Stage':'In/Thru Screen',
 'JKCF_-_Return_1_for_In_Thru_Interview_Stage':'In/Thru Interview',
 'JKCF_-_Return_1_for_In_Thru_Offer_Stage':'In/Thru Offer',
 'JKCF_-_Return_1_for_In_Thru_Background_Check_Stage':'In/Thru Background Check',
 'JKCF_-_Return_1_for_In_Thru_Ready_for_Hire_Stage':'In/Thru Ready for Hire'})

In [18]:
alp_candidates.to_csv(r'O:\people_analytics\scorecards_kpis\ldp\data_build\alp_candidates_export.csv')

# Turnover

In [20]:
recordstart = '2021-01-01'
recordend = '2021-12-31'

In [21]:
turnover = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Trended_Worker_Turnover_Details?IncludeSubOrgs=1&Active=0&Record_Start={0}-08%3A00&Remove_Exclude_From_HC=0&Record_End={1}-08%3A00&SupervisoryOrg%21WID=fad8c8a44c4510541494e34161d00311&format=csv'.format(recordstart,recordend)
with requests.Session() as s:
    download = s.get(turnover, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    turnover = pd.read_csv(io.StringIO(decoded_content))
    turnover = turnover.set_index('Emplid')

C:\Users\DDY17\Anaconda3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (11,12,13,80) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [22]:
print(turnover.shape)
turnover.head()

(52551, 143)

,Year-Quarter,Month,Record_Date,Record_Type,LAN_ID,Preferred_Name,Worker,Work_Email,Hire,OriginalHireAtRecordDate,Term_Event,Term_Category,Term_Reason,Secondary_Term_Reason,Is_Term_90-Day,Is_Term_New_Hire,Is_Rehire_Eligible,Tenure,Years_of_Service,Age_Group,Age,Diverse,Gender,Gender_Identity,Sexual_Orientation,Pronoun,Ethnicity,Hispanic_Latino,Minority,MinorityStatus,Disability,DisabilityStatus,Disability_Self_ID,Veteran,VeteranStatus,MilitaryStatus,Highest_Degree,On_Leave,Active,Management_Level,Job_Level,Job_Family_Group,Job_Family,Job_Code,Job_Profile,Business_Title,YearsInJobAtRecordDate,Years_In_Job,Time_in_Job,Position_ID,Grade,Annual_Salary,Annual_FTE_Salary,Salary_Range_Minimum,Salary_Range_Midpoint,Salary_Range_Maximum,Is_Org_Manager,Is_People_Manager,Direct_Reports,FTE,Exempt,Full_Part_Time,Worker_Type,Employee_Type,Contingent_Type,Potential,Company,Country,Campus,Location,Work_Address_State,Business_Area,Profile_Area,Department,Consolidated_Area,Area,Sub_Area,Cost_Center_ID,Cost_Center,BP_Type,End_Headcount,Hires,Promotion,Transfer_Out,Transfer_In,Termination,Voluntary_Termination,Involuntary_Termination,SupervisoryOrgID,SupervisoryOrg,OrgManager,OrgLevel,OrgLevel01ID,OrgLevel01,OrgLevel01Manager,OrgLevel02ID,OrgLevel02,OrgLevel02Manager,OrgLevel03ID,OrgLevel03,OrgLevel03Manager,OrgLevel04ID,OrgLevel04,OrgLevel04Manager,OrgLevel05ID,OrgLevel05,OrgLevel05Manager,OrgLevel06ID,OrgLevel06,OrgLevel06Manager,OrgLevel07ID,OrgLevel07,OrgLevel07Manager,OrgLevel08ID,OrgLevel08,OrgLevel08Manager,OrgLevel09ID,OrgLevel09,OrgLevel09Manager,OrgLevel10ID,OrgLevel10,OrgLevel10Manager,Manager_Location,Supervisory_Org_L1_Away,Supervisory_Org_L2_Away,Supervisory_Org_L3_Away,Supervisory_Org_L4_Away,Supervisory_Org_L5_Away,Supervisory_Org_L6_Away,Supervisory_Org_L7_Away,Supervisory_Org_L8_Away,Supervisory_Org_L9_Away,Supervisory_Org_L10_Away,Worker_Supervisory_Org_L1,Worker_Supervisory_Org_L2,Worker_Supervisory_Org_L3,Worker_Supervisory_Org_L4,Worker_Supervisory_Org_L5,Worker_Supervisory_Org_L6,Worker_Supervisory_Org_L7,Worker_Supervisory_Org_L8,Worker_Supervisory_Org_L9,Worker_Supervisory_Org_L10
Emplid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
32773,2021-Q1,1,2021-01-01,Activity,#SDINBM,Ben Miller,Ben Miller (Terminated),BMiller@UNUM.COM,1987-03-16,1987-03-16,Terminate Employee,Job Elimination/Redundancy,No Placement,NaN,0,0,Yes,25+ Years,33.79,60 and over,68,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Masters,0,0,1 Senior Leader,1.3 VP & Equivalent,Other Job Families,Investments,IN200-USA,"VP, Sr. Managing Director (inactive)",NaN,20.99,20-24 Years,"20 year(s), 11 month(s), 30 day(s)",NaN,17,244120.0,244120.0,180300,265911.2064,351600,1,0,0,1.0,1,Full time,Employee,Regular,NaN,Well Placed,"C3004 Provident Investment Management, LLC",United States of America,Chattanooga,Chattanooga Home Office,NaN,Corporate Staff Direct,Corporate Investments,Investments,Asset Management,Asset Mgmt,Asset_Management,EC0901,NaN,Termination,0,0,0,0,0,1,0,1,SupOrg_00210934,Investments,Martha Leiper,3,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00210934,Investments,Martha Leiper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chattanooga Home Office,Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30477,2021-Q1,1,2021-01-01,Activity,H071JTM,John McHugh,John McHugh (Terminated),JMcHugh@UNUM.COM,1986-11-12,1986-11-12,Terminate Employee,Job Elimination/Redundancy,No Placement,NaN,0,0,NaN,25+ Years,34.14,55 - 59,59,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,0,5 Individual Contributor,6 Entry-Level,NaN,Supply/Procurement,SM703-USA,Logistics Specialist,NaN,3.02,02-05 Years,"3 year(s), 0 month(s), 7 day(s)",NaN,5,36508.0,36508.0,31200,40650.0000,50100,0,0,0,1.0,0,Full time,Employee,Regular,NaN,NaN,C3035 Unum Group,United States of America,Worcester,Worcester Home Office,NaN,Corporate Services,Corp Services,"Imaging, Records Mgt & Mail",Imag_Records Mgmt and Mail,"Imaging, Records Mgnt, Mail","Imaging, Records Manage_Mail",EC0351,NaN,Termination,0,0,0,0,0,1,0,1,SupOrg_00116642,Global Services Print & Distrib,Richard Meadows,7,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00211048,Unum Law & Audit,Lisa Iglesias,SupOrg_00217071,Corporate Services,Wendy Gibson,SupOrg_00202805,Real Estate Management,Richard Meadows,SupOrg_00300120,Global Services Print & Distrib,Richard Meadows,SupOrg_00116642,Global Services Print & Distrib,Richard Meadows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chattanooga Home Office,Global Services Print & Distrib (Richard Meado...,Real Estate Management (Richard Meadows),Corporate Services (Wendy Gibson),Unum Law & Audit (Lisa Iglesias),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586,2021-Q1,1,2021-01-01,Activity,C1RGF,Randall Ford,Randall Ford (Terminated),rford@unum.com,1981-06-25,1981-06-25,Terminate Employee,Job Elimination/Redundancy,No Placement,NaN,0,0,NaN,25+ Years,39.52,60 and over,61,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Bachelors,0,0,1 Senior Leader,1.3 VP & Equivalent,Marketing Group,Marketing,PR237-USA,"VP, NCG Marketing & Distrib",NaN,6.16,05-10 Years,"6 year(s), 1 month(s), 30 day(s)",NaN,16,176000.0,176000.0,132700,182500.0000,232200,1,0,0,1.0,1,Full time,Employee,Regular,NaN,Well Placed,C3035 Unum Group,United States of America,Portland,Portland Home Office,NaN,US Operations,Unum US Growth Ops & Group Benefits,Unum US_National Client Group,National Client Group,NCG Market Development,Market Development,EC1038,NaN,Termination,0,0,0,0,0,1,0,1,SupOrg_00219654,National Client Group,John King,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00115378,Unum Group Benefits,Chris Pyne,SupOrg_00219654,National Client Group,John King,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portland Home Office,Unum Group Benefits (Chris Pyne),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1282,2021-Q1,1,2021-01-01,Activity,C1RCL,Randy Laverriere,Randy Laverriere (Terminated),rlaverriere@unum.com,1983-03-14,1983-03-14,Terminate Employee,Voluntary,Retirement,NaN,0,0,Yes,25+ Years,37.80,60 and over,60,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Bachelors,0,0,4 Senior Individual Contributor,3 Managers,NaN,Finance,FI679-USA,Senior Financial Analyst,NaN,3.21,02-05 Years,"3 year(s), 2 month(s), 16 day(s)",NaN,12,47622.0,190488.0,60100,81100.0000,102200,0,0,0,0.5,1,Part time,Employee,Regular,NaN,NaN,C3035 Unum Group,United States of America,Portland,Portland Home Office,NaN,Corporate Staff Direct,Corporate Finance and Closed Block,Finance,Transformation Mgmt Office,Business Performance,Bus Performance,EC9594,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00117136,Enterprise Finance Operational Reporting & Ana...,Pamela Carpenter,7,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00214583TOP,Enterprise Finance,Steven Zabel,SupOrg_00214583,Finance,Steven Zabel,SupOrg_00218043,Transformation Management Office,Stephen Mitchell,SupOrg_102324,TMO Organization,Sandra Sincero,SupOrg_00117136,Enterprise Finance Operational Reporting & Ana...,Pamela Carpenter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portland Home Office,TMO Organization (Sandra Sincero),Transformation Management Office (Stephen Mitc...,Finance (Steven Zabel),Enterprise Finance (Steven Zabel),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34087,2021-Q1,1,2021-01-01,Activity,JPN0K,Kien Ngo,Kien Ngo (Terminated),KNgo@UNUM.COM,1982-02-01,1982-02-01,Terminate Employee,Voluntary,Retirement,NaN,0,0,NaN,25+ Years,38.92,60 and over,60,1,Female,NaN,NaN,NaN,Asian (United States of America),0,1,Minority,0,NaN,NaN,0,NaN,NaN,Bachelors,0,0,5 Individual Contributor,6 Entry-Level,NaN,Customer Services,CS401-USA,IDI Service Specialist I,NaN,5.82,05-10 Years,"5 year(s), 9 month(s), 23 day(s)",NaN,8,50134.0,50134.0,38300,50703.4080,63100,0,0,0,1.0,0,Full time,Employee,Regular,NaN,Well Placed,C3035 Unum Group,United States of America,Home Workers - US,Home Worker - US,Massachusetts,US Operations,Unum US Client Success,Unum US_Client Success,IDI Policy Services,Policy Services,IDI_Policy Services,EC0681,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00217735,Unum US IDI Policy Services,Linda Belezarian,6,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00212508,Unum US Client Success,Liz Rickett,SupOrg_00216968,"Unum US IDI Policy & Practice, Training & QR",Jennifer Robare,SupOrg_00217735,Unum US IDI Policy Services,Linda Belezarian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home Worker - US,"Unum US IDI Policy & Practice, Training & QR (...",Unum US Client Success (Liz Rickett),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
recordstart = '2020-01-01'
recordend = '2020-06-30'

In [24]:
turnover2 = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Trended_Worker_Turnover_Details?IncludeSubOrgs=1&Active=0&Record_Start={0}-08%3A00&Remove_Exclude_From_HC=0&Record_End={1}-08%3A00&SupervisoryOrg%21WID=fad8c8a44c4510541494e34161d00311&format=csv'.format(recordstart,recordend)
with requests.Session() as s:
    download = s.get(turnover2, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    turnover2 = pd.read_csv(io.StringIO(decoded_content))
    turnover2 = turnover2.set_index('Emplid')

C:\Users\DDY17\Anaconda3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (11,12,13,14,80) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [25]:
print(turnover2.shape)
turnover2.head()

(86903, 143)

,Year-Quarter,Month,Record_Date,Record_Type,LAN_ID,Preferred_Name,Worker,Work_Email,Hire,OriginalHireAtRecordDate,Term_Event,Term_Category,Term_Reason,Secondary_Term_Reason,Is_Term_90-Day,Is_Term_New_Hire,Is_Rehire_Eligible,Tenure,Years_of_Service,Age_Group,Age,Diverse,Gender,Gender_Identity,Sexual_Orientation,Pronoun,Ethnicity,Hispanic_Latino,Minority,MinorityStatus,Disability,DisabilityStatus,Disability_Self_ID,Veteran,VeteranStatus,MilitaryStatus,Highest_Degree,On_Leave,Active,Management_Level,Job_Level,Job_Family_Group,Job_Family,Job_Code,Job_Profile,Business_Title,YearsInJobAtRecordDate,Years_In_Job,Time_in_Job,Position_ID,Grade,Annual_Salary,Annual_FTE_Salary,Salary_Range_Minimum,Salary_Range_Midpoint,Salary_Range_Maximum,Is_Org_Manager,Is_People_Manager,Direct_Reports,FTE,Exempt,Full_Part_Time,Worker_Type,Employee_Type,Contingent_Type,Potential,Company,Country,Campus,Location,Work_Address_State,Business_Area,Profile_Area,Department,Consolidated_Area,Area,Sub_Area,Cost_Center_ID,Cost_Center,BP_Type,End_Headcount,Hires,Promotion,Transfer_Out,Transfer_In,Termination,Voluntary_Termination,Involuntary_Termination,SupervisoryOrgID,SupervisoryOrg,OrgManager,OrgLevel,OrgLevel01ID,OrgLevel01,OrgLevel01Manager,OrgLevel02ID,OrgLevel02,OrgLevel02Manager,OrgLevel03ID,OrgLevel03,OrgLevel03Manager,OrgLevel04ID,OrgLevel04,OrgLevel04Manager,OrgLevel05ID,OrgLevel05,OrgLevel05Manager,OrgLevel06ID,OrgLevel06,OrgLevel06Manager,OrgLevel07ID,OrgLevel07,OrgLevel07Manager,OrgLevel08ID,OrgLevel08,OrgLevel08Manager,OrgLevel09ID,OrgLevel09,OrgLevel09Manager,OrgLevel10ID,OrgLevel10,OrgLevel10Manager,Manager_Location,Supervisory_Org_L1_Away,Supervisory_Org_L2_Away,Supervisory_Org_L3_Away,Supervisory_Org_L4_Away,Supervisory_Org_L5_Away,Supervisory_Org_L6_Away,Supervisory_Org_L7_Away,Supervisory_Org_L8_Away,Supervisory_Org_L9_Away,Supervisory_Org_L10_Away,Worker_Supervisory_Org_L1,Worker_Supervisory_Org_L2,Worker_Supervisory_Org_L3,Worker_Supervisory_Org_L4,Worker_Supervisory_Org_L5,Worker_Supervisory_Org_L6,Worker_Supervisory_Org_L7,Worker_Supervisory_Org_L8,Worker_Supervisory_Org_L9,Worker_Supervisory_Org_L10
Emplid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
32489,2020-Q1,1,2020-01-01,Activity,#ADAUMT,Marty Turner,Marty Turner (Terminated),martyturner@unum.com,1974-09-10,1974-09-10,Terminate Employee,Voluntary,Retirement,NaN,0,0,No,25+ Years,45.31,60 and over,63,1,Female,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,0,5 Individual Contributor,5.2 Professional - Individual Contributor,Information Technology,Information Technology Jobs,IT792-USA,"Test Engineer I, US",NaN,4.66,05-10 Years,"4 year(s), 7 month(s), 28 day(s)",NaN,11,62603.00,62603.0,56600,82071.36000,107500,0,0,0,1.0,1,Full time,Employee,Regular,NaN,Well Placed,C3035 Unum Group,United States of America,Chattanooga,Chattanooga Home Office,NaN,Information Technology,Information Tech,Colonial IT,CLA IT,Product Tech CLA,US - CLA Product Tech,EC1794,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00289511,CLA: Product Value Stream,David Bateman,6,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00302588,Information Technology,Gautam Roy,SupOrg_00307100,Data and Analytics,Apparsamy Balaji,SupOrg_00289511,CLA: Product Value Stream,David Bateman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colonial Life Home Office,Data and Analytics (Apparsamy Balaji),Information Technology (Gautam Roy),Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38583,2020-Q1,1,2020-01-01,Activity,AYP18,Callum Aitken,Callum Aitken,Callum.AITKEN@unum.co.uk,2018-04-03,2003-10-27,NaN,NaN,NaN,NaN,0,0,NaN,01 - 02 Years,1.74,40 - 44,40,0,Male,NaN,NaN,NaN,White (United Kingdom) (inactive),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Bachelors,0,1,5 Individual Contributor,5.2 Professional - Individual Contributor,NaN,Customer Services,SC042-UK,"Broker Services, Senior Specialist",Claim Management Spec III,0.00,01-02 Years,"0 year(s), 5 month(s), 30 day(s)",312548.0,9,35757.54,27300.0,20000,26000.00000,32000,0,0,0,1.0,0,Full time,Employee,Regular,NaN,NaN,C5094 Unum European Holding Company Limited,United Kingdom,Dorking,Dorking,Surrey,Unum UK,Unum UK Direct,Unum UK Customer Services,Broker Services,Broker_Services,Regional.,EC7026,Claims,Transfer Employee,0,0,0,1,0,0,0,0,SupOrg_00051422,UK Broker Services,Michelle Garfield,8,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00051934,Unum International,Mark Till,SupOrg_00293589,Unum UK Customer Services,Liz Walker,SupOrg_00220960,UK Broker Services,James Vallender,SupOrg_00303502,UK Broker Services,Karen Blatchford,SupOrg_00051422,UK Broker Services,Michelle Garfield,NaN,NaN,NaN,NaN,NaN,NaN,Dorking,UK Broker Services (Karen Blatchford),UK Broker Services (James Vallender),Unum UK Customer Services (Liz Walker),Unum International (Mark Till),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,Unum Executive (Rick McKenney),Unum Group (Rick McKenney),Unum Group COO (Michael Simonds),Unum International (Mark Till),Unum UK Customer Services (Liz Walker),Claims Rehab & Medical Services (Paula Coffey),Claims (Sarah Gilbey),UK Customer Care Services (Nicola Ansell),NaN,NaN
89147,2020-Q1,1,2020-01-01,Activity,B6F15,Kelli Abramson,Kelli Abramson (Terminated),KAbramson@ColonialLife.com,2015-11-23,2015-11-23,Terminate Employee,Voluntary,Personal,NaN,0,0,NaN,02 - 05 Years,4.11,25 - 29,29,1,Female,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,0,2 Leader,3 Managers,NaN,Customer Services,DI396-USA,National Recruiting Program Manager,NaN,0.74,01-02 Years,"0 year(s), 8 month(s), 24 day(s)",NaN,12,78000.00,78000.0,60100,81100.00000,102200,0,0,0,1.0,1,Full time,Employee,Regular,NaN,Well Placed,C3035 Unum Group,United States of America,Columbia,Colonial Life Home Office,NaN,US Operations,Colonial Life,CLA Sales,Distribution Development,National_Recruiting,Recruiting_Teams,EC6231,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00200312,Colonial Life Field Development,Jennifer Davis,7,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00210462,VB & Colonial Life,Tim Arnold,SupOrg_00221275,Field & Market Development,Richard Shaffer,SupOrg_00213998,Colonial Life Sales Mgmt Performance,Michelle White,SupOrg_00200312,Colonial Life Field Development,Jennifer Davis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colonial Life Home Office,Colonial Life Sales Mgmt Performance (Michelle...,Field & Market Development (Richard Shaffer),VB & Colonial Life (Tim Arnold),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55538,2020-Q1,1,2020-01-01,Activity,CNZ04,Jacki Grano,Jacki Grano (Terminated),JGrano@UNUM.COM,2004-04-15,2004-04-15,Terminate Employee,Voluntary,Retirement,NaN,0,0,Yes,15 - 20 Years,15.71,60 and over,65,1,Female,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,0,3 Management,2 Directors,Information Technology,Information Technology Jobs,IT821-USA,"Director, IT Delivery, US",NaN,1.08,02-05 Years,"1 year(s), 0 month(s), 29 day(s)",NaN,14,112229.00,112229.0,96100,141819.31008,187400,1,0,0,1.0,1,Full time,Employee,Regular,NaN,Well Placed,C3035 Unum Group,United States of America,Portland,Portland Home Office,NaN,Information Technology,Information Tech,Office Of CTO,Infrastructure - IT,Infra - DICE,DICE Staff_2,EC9080,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00303218,End User Services,Blake Pease,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00302588,Information Technology,Gautam Roy,SupOrg_00303218,End User Services,Blake Pease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portland Home Office,Information Technology (Gautam Roy),Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42940,2020-Q1,1,2020-01-01,Activity,#SPRMRW,Rachel Woods,Rachel Woods (Terminated),rwoods@unum.com,2000-05-01,2000-05-01,Terminate Employee,Voluntary,Retirement,NaN,0,0,NaN,15 - 20 Years,19.67,60 and over,81,1,Female,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,0,5 Individual Contributor,6 Entry-Level,NaN,Operational Support,CC816-USA,Intake Service Specialist I,NaN,2.02,02-05 Years,"2 year(s), 0 month(s), 7 day(s)",NaN,5,31200.00,31200.0,31200,37400.00000,43600,0,0,0,1.0,0,Full time,Employee,Regular,NaN,Well Placed,C3035 Unum Group,United States of America,Home Workers - US,Home Worker - US,Tennessee,US Operations,Unum US Benefits Center,Unum US Benefits AMC and CEC,UUS Customer Experience Center,UUS Cust & Ben Support,Unum Intake,EC8774,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00116902,Unum US Customer & Benefits Support,Lissa Lewis,7,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00309192,Customer Experience Center/Absence Management ...,Michelle Boucher,SupOrg_00219796,US Contact Centers,Preston Rogers,SupOrg_312004,Unum US Customer & Benefits Support,Liz DiSotto,SupOrg_00116902,Unum US Customer & Benefits Support,Lissa Lewis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portland Home Office,Unum US Customer & Benefits Support (Liz DiSotto),US Contact Centers (Preston Rogers),Customer Experience Center/Absence Management ...,Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
recordstart = '2020-07-01'
recordend = '2020-12-31'

In [27]:
turnover3 = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Trended_Worker_Turnover_Details?IncludeSubOrgs=1&Active=0&Record_Start={0}-08%3A00&Remove_Exclude_From_HC=0&Record_End={1}-08%3A00&SupervisoryOrg%21WID=fad8c8a44c4510541494e34161d00311&format=csv'.format(recordstart,recordend)
with requests.Session() as s:
    download = s.get(turnover3, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    turnover3 = pd.read_csv(io.StringIO(decoded_content))
    turnover3 = turnover3.set_index('Emplid')

C:\Users\DDY17\Anaconda3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (11,12,13,80) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [28]:
print(turnover3.shape)
turnover3.head()

(83721, 143)

,Year-Quarter,Month,Record_Date,Record_Type,LAN_ID,Preferred_Name,Worker,Work_Email,Hire,OriginalHireAtRecordDate,Term_Event,Term_Category,Term_Reason,Secondary_Term_Reason,Is_Term_90-Day,Is_Term_New_Hire,Is_Rehire_Eligible,Tenure,Years_of_Service,Age_Group,Age,Diverse,Gender,Gender_Identity,Sexual_Orientation,Pronoun,Ethnicity,Hispanic_Latino,Minority,MinorityStatus,Disability,DisabilityStatus,Disability_Self_ID,Veteran,VeteranStatus,MilitaryStatus,Highest_Degree,On_Leave,Active,Management_Level,Job_Level,Job_Family_Group,Job_Family,Job_Code,Job_Profile,Business_Title,YearsInJobAtRecordDate,Years_In_Job,Time_in_Job,Position_ID,Grade,Annual_Salary,Annual_FTE_Salary,Salary_Range_Minimum,Salary_Range_Midpoint,Salary_Range_Maximum,Is_Org_Manager,Is_People_Manager,Direct_Reports,FTE,Exempt,Full_Part_Time,Worker_Type,Employee_Type,Contingent_Type,Potential,Company,Country,Campus,Location,Work_Address_State,Business_Area,Profile_Area,Department,Consolidated_Area,Area,Sub_Area,Cost_Center_ID,Cost_Center,BP_Type,End_Headcount,Hires,Promotion,Transfer_Out,Transfer_In,Termination,Voluntary_Termination,Involuntary_Termination,SupervisoryOrgID,SupervisoryOrg,OrgManager,OrgLevel,OrgLevel01ID,OrgLevel01,OrgLevel01Manager,OrgLevel02ID,OrgLevel02,OrgLevel02Manager,OrgLevel03ID,OrgLevel03,OrgLevel03Manager,OrgLevel04ID,OrgLevel04,OrgLevel04Manager,OrgLevel05ID,OrgLevel05,OrgLevel05Manager,OrgLevel06ID,OrgLevel06,OrgLevel06Manager,OrgLevel07ID,OrgLevel07,OrgLevel07Manager,OrgLevel08ID,OrgLevel08,OrgLevel08Manager,OrgLevel09ID,OrgLevel09,OrgLevel09Manager,OrgLevel10ID,OrgLevel10,OrgLevel10Manager,Manager_Location,Supervisory_Org_L1_Away,Supervisory_Org_L2_Away,Supervisory_Org_L3_Away,Supervisory_Org_L4_Away,Supervisory_Org_L5_Away,Supervisory_Org_L6_Away,Supervisory_Org_L7_Away,Supervisory_Org_L8_Away,Supervisory_Org_L9_Away,Supervisory_Org_L10_Away,Worker_Supervisory_Org_L1,Worker_Supervisory_Org_L2,Worker_Supervisory_Org_L3,Worker_Supervisory_Org_L4,Worker_Supervisory_Org_L5,Worker_Supervisory_Org_L6,Worker_Supervisory_Org_L7,Worker_Supervisory_Org_L8,Worker_Supervisory_Org_L9,Worker_Supervisory_Org_L10
Emplid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
74928,2020-Q3,7,2020-07-01,Activity,GDX13,Andrew Philips,Andrew Philips,Andrew.PHILIPS@unum.co.uk,2013-07-15,2013-07-15,NaN,NaN,NaN,NaN,0,0,NaN,05 - 10 Years,6.96,25 - 29,29,0,Male,NaN,NaN,NaN,White (United Kingdom) (inactive),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,1,5 Individual Contributor,5.2 Professional - Individual Contributor,NaN,Customer Services,SC043-UK,"Broker Services, Lead Specialist",Financial Analyst - FP&A,0.00,00-01 Years,"4 year(s), 2 month(s), 29 day(s)",317664.0,10,39804.54,31775.0,24100,32000.00,39900,0,0,0,1.0,0,Full time,Employee,Regular,NaN,NaN,C5094 Unum European Holding Company Limited,United Kingdom,Basingstoke,Basingstoke,Surrey,Unum UK,Unum UK Direct,Unum UK Customer Services,Broker Services,Broker_Services,Brkr Srvcs,EC7054,Strategy & Planning,Transfer Employee,0,0,0,1,0,0,0,0,SupOrg_00310439,UK Broker Services,Marie Sheffield,8,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00051934,Unum International,Mark Till,SupOrg_00293589,Unum UK Customer Services,Liz Walker,SupOrg_00220960,UK Broker Services,James Vallender,SupOrg_00303500,UK Broker Services,Louise Cauchie,SupOrg_00310439,UK Broker Services,Marie Sheffield,NaN,NaN,NaN,NaN,NaN,NaN,Dorking,UK Broker Services (Louise Cauchie),UK Broker Services (James Vallender),Unum UK Customer Services (Liz Walker),Unum International (Mark Till),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,Unum Executive (Rick McKenney),Unum Group (Rick McKenney),Unum Group COO (Michael Simonds),Unum International (Mark Till),UK_Finance & Underwriting (Jon Fletcher),UK Financial Control (Deirdre Flood),UK Financial Planning and Analysis (Deirdre Fl...,UK Financial Planning and Analysis (Graham Cop...,NaN,NaN
9327,2020-Q3,7,2020-07-01,Activity,C5S2M,Sara May,Sara May (Terminated),smay@unum.com,1996-04-29,1996-04-29,Terminate Employee,Voluntary,Retirement,NaN,0,0,Yes,20 - 24 Years,24.17,60 and over,65,1,Female,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Other,0,0,5 Individual Contributor,5.2 Professional - Individual Contributor,NaN,Claims,CC888-USA,Sr. Benefits Coordinator,NaN,0.54,01-02 Years,"0 year(s), 6 month(s), 15 day(s)",NaN,8,25063.50,100254.0,33300,44089.92,54900,0,0,0,0.5,0,Part time,Employee,Regular,NaN,NaN,C3035 Unum Group,United States of America,Portland,Portland Home Office,NaN,US Operations,Unum US Benefits Center,Unum US Benefits Operations,LTC Benefits Operations,LTC Benefits Ops,Long-Term Care Benefits,EC8418,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00208156,Closed Block LTC Benefits Operations,Jon Colson,8,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00216660,Unum US Benefits Operations,Lori Whynot,SupOrg_00117105,Unum US Group Life & LTC Benefits,Michelle Bryer,SupOrg_00294234,Closed Block LTC Benefits Operations,Stephanie Perry,SupOrg_00214191,Closed Block LTC Benefits Operations,John Noble,SupOrg_00208156,Closed Block LTC Benefits Operations,Jon Colson,NaN,NaN,NaN,NaN,NaN,NaN,Portland Home Office,Closed Block LTC Benefits Operations (John Noble),Closed Block LTC Benefits Operations (Stephani...,Unum US Group Life & LTC Benefits (Michelle Br...,Unum US Benefits Operations (Lori Whynot),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21204,2020-Q3,7,2020-07-01,Activity,C9LMM,Mike Miller,Mike Miller (Terminated),lmmiller@coloniallife.com,1976-03-01,1976-03-01,Terminate Employee,Job Elimination/Redundancy,No Placement,NaN,0,0,No,25+ Years,44.33,60 and over,66,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,"NO, I DON'T HAVE A DISABILITY",0,NaN,NaN,Bachelors,0,0,1 Senior Leader,1.3 VP & Equivalent,NaN,Customer Services,DI238-USA,"VP, Sales Compensation, Incentives & Support (...",NaN,7.49,05-10 Years,"7 year(s), 5 month(s), 29 day(s)",NaN,16,200000.00,200000.0,132700,182500.00,232200,0,0,0,1.0,1,Full time,Employee,Regular,NaN,Well Placed,C3035 Unum Group,United States of America,Columbia,Colonial Life Home Office,NaN,US Operations,Colonial Life,CLA Growth and Risk Operations,"Growth & Risk Ops Support, Reporting and Compl...",Growth and Risk Ops Admin,Grwth and Risk Ops Admin,EC6088,NaN,Termination,0,0,0,0,0,1,0,1,SupOrg_00284224,Colonial Life Growth Operations,Tim Arnold,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00210462,VB & Colonial Life,Tim Arnold,SupOrg_00284224,Colonial Life Growth Operations,Tim Arnold,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VB & Colonial Life (Tim Arnold),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33490,2020-Q3,7,2020-07-01,Activity,C0MXK,Mike Keller,Mike Keller (Terminated),MLKeller@ColonialLife.com,1988-02-11,1988-02-11,Terminate Employee,Voluntary,Retirement,NaN,0,0,NaN,25+ Years,32.39,60 and over,63,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Bachelors,0,0,1 Senior Leader,1.3 VP & Equivalent,NaN,Sales (Incentives),SA242-USA,"VP, Sales, CL - Southwest",NaN,13.82,10-15 Years,"13 year(s), 9 month(s), 29 day(s)",NaN,17,254300.00,254300.0,0,0.00,0,1,0,0,1.0,1,Full time,Employee,Regular,NaN,High Impact Leader at Current Level,C3035 Unum Group,United States of America,US Sales Offices,Plano Sales - CLA,NaN,US Operations,Colonial Life,CLA Sales,Sales Offices,TSM Sales Offices Southwest Region,SW Territory Sales Offices,EC6256,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00210487,Colonial Life Sales,William Deehan,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00210462,VB & Colonial Life,Tim Arnold,SupOrg_00210487,Colonial Life Sales,William Deehan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Roswell Sales - CLA,VB & Colonial Life (Tim Arnold),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89973,2020-Q3,7,2020-07-01,Activity,ATA16,David Allen,David Allen (Terminated),DALLEN1@UNUM.com,2016-05-23,2016-05-23,Terminate Employee,Voluntary,Other Position,NaN,0,0,NaN,02 - 05 Years,4.10,25 - 29,28,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Bachelors,0,0,5 Individual Contributor,5.2 Professional - Individual Contributor,Information Technology,Information Technology Jobs,IT790-USA,"Software Engineer I, US",NaN,2.71,02-05 Years,"2 year(s), 8 month(s), 15 day(s)",NaN,11,68071.00,68071.0,56600,82071.36,107500,0,0,0,1.0,1,Full time,Employee,Regular,NaN,Likely in Wrong Role/Level,C3035 Unum Group,United States of America,Chattanooga,Chattanooga Home Office,NaN,Information Technology,Information Tech,Office Of CTO,Benefits Technology,UUS Benefits,US - UUS Benefits,EC1700,NaN,Termination,0,0,0,0,0,1,1,0,SupOrg_00289610,Benefits Tech,Daniela LaCelle,6,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00302588,Information Technology,Gautam Roy,SupOrg_00320123,Benefit & Contact Center Journey Tech,Mike Schubert,SupOrg_00289610,Benefits Tech,Daniela LaCelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chattanooga Home Office,Benefit & Contact Center Journey Tech (Mike Sc...,Information Technology (Gautam Roy),Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
recordstart = '2019-01-01'
recordend = '2019-06-30'

In [30]:
turnover4 = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Trended_Worker_Turnover_Details?IncludeSubOrgs=1&Active=0&Record_Start={0}-08%3A00&Remove_Exclude_From_HC=0&Record_End={1}-08%3A00&SupervisoryOrg%21WID=fad8c8a44c4510541494e34161d00311&format=csv'.format(recordstart,recordend)
with requests.Session() as s:
    download = s.get(turnover4, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    turnover4 = pd.read_csv(io.StringIO(decoded_content))
    turnover4 = turnover4.set_index('Emplid')

C:\Users\DDY17\Anaconda3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (11,12,13,80) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [31]:
print(turnover4.shape)
turnover4.head()

(80109, 143)

,Year-Quarter,Month,Record_Date,Record_Type,LAN_ID,Preferred_Name,Worker,Work_Email,Hire,OriginalHireAtRecordDate,Term_Event,Term_Category,Term_Reason,Secondary_Term_Reason,Is_Term_90-Day,Is_Term_New_Hire,Is_Rehire_Eligible,Tenure,Years_of_Service,Age_Group,Age,Diverse,Gender,Gender_Identity,Sexual_Orientation,Pronoun,Ethnicity,Hispanic_Latino,Minority,MinorityStatus,Disability,DisabilityStatus,Disability_Self_ID,Veteran,VeteranStatus,MilitaryStatus,Highest_Degree,On_Leave,Active,Management_Level,Job_Level,Job_Family_Group,Job_Family,Job_Code,Job_Profile,Business_Title,YearsInJobAtRecordDate,Years_In_Job,Time_in_Job,Position_ID,Grade,Annual_Salary,Annual_FTE_Salary,Salary_Range_Minimum,Salary_Range_Midpoint,Salary_Range_Maximum,Is_Org_Manager,Is_People_Manager,Direct_Reports,FTE,Exempt,Full_Part_Time,Worker_Type,Employee_Type,Contingent_Type,Potential,Company,Country,Campus,Location,Work_Address_State,Business_Area,Profile_Area,Department,Consolidated_Area,Area,Sub_Area,Cost_Center_ID,Cost_Center,BP_Type,End_Headcount,Hires,Promotion,Transfer_Out,Transfer_In,Termination,Voluntary_Termination,Involuntary_Termination,SupervisoryOrgID,SupervisoryOrg,OrgManager,OrgLevel,OrgLevel01ID,OrgLevel01,OrgLevel01Manager,OrgLevel02ID,OrgLevel02,OrgLevel02Manager,OrgLevel03ID,OrgLevel03,OrgLevel03Manager,OrgLevel04ID,OrgLevel04,OrgLevel04Manager,OrgLevel05ID,OrgLevel05,OrgLevel05Manager,OrgLevel06ID,OrgLevel06,OrgLevel06Manager,OrgLevel07ID,OrgLevel07,OrgLevel07Manager,OrgLevel08ID,OrgLevel08,OrgLevel08Manager,OrgLevel09ID,OrgLevel09,OrgLevel09Manager,OrgLevel10ID,OrgLevel10,OrgLevel10Manager,Manager_Location,Supervisory_Org_L1_Away,Supervisory_Org_L2_Away,Supervisory_Org_L3_Away,Supervisory_Org_L4_Away,Supervisory_Org_L5_Away,Supervisory_Org_L6_Away,Supervisory_Org_L7_Away,Supervisory_Org_L8_Away,Supervisory_Org_L9_Away,Supervisory_Org_L10_Away,Worker_Supervisory_Org_L1,Worker_Supervisory_Org_L2,Worker_Supervisory_Org_L3,Worker_Supervisory_Org_L4,Worker_Supervisory_Org_L5,Worker_Supervisory_Org_L6,Worker_Supervisory_Org_L7,Worker_Supervisory_Org_L8,Worker_Supervisory_Org_L9,Worker_Supervisory_Org_L10
Emplid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
93856,2019-Q1,1,2019-01-01,Activity,BTP17,Layak Singh,Layak Singh [C] (Contract Ended),LSingh@ColonialLife.com,2017-08-02,2017-08-02,End Contingent Worker Contract,Voluntary,Personal,NaN,0,0,NaN,01 - 02 Years,1.41,24 and under,0,0,NaN,NaN,NaN,NaN,NaN,0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,0,NaN,NaN,Contingent Workers,Contingent Worker Jobs,CW001,Contract Service Worker,NaN,1.41,02-05 Years,"1 year(s), 4 month(s), 29 day(s)",NaN,NaN,0.0,0.0,0,0,0,0,0,0,1.0,0,Full time,Contingent Worker,NaN,Vendor - Contract Labor,NaN,C3035 Unum Group,United States of America,International,International,NaN,US Operations,Unum US Benefits Center,CLA Claims,Claims,Claims Ops,Claims Operations,EC6217,NaN,End Contingent Worker Contract,0,0,0,0,0,1,1,0,SupOrg_00295931,Colonial Life A&H/Life/Cancer Claims,Michelle Boucher,6,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00309192,Customer Experience Center/Absence Management ...,Michelle Boucher,SupOrg_00000505,Colonial Life Disability Claims,Michelle Boucher,SupOrg_00295931,Colonial Life A&H/Life/Cancer Claims,Michelle Boucher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colonial Life Home Office,Colonial Life Disability Claims (Michelle Bouc...,Customer Experience Center/Absence Management ...,Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53214,2019-Q1,1,2019-01-01,Activity,$ITDT,Daniel Taber,Daniel Taber (Terminated),DTaber@UNUM.COM,2003-03-17,2003-03-17,Terminate Employee,Job Elimination/Redundancy,No Placement,NaN,0,0,NaN,15 - 20 Years,15.79,60 and over,60,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Bachelors,0,0,3 Management,2 Directors,Information Technology,Information Technology Jobs,IT803-USA,"Technology Capability Manager, US (inactive)",NaN,3.66,05-10 Years,"3 year(s), 7 month(s), 28 day(s)",NaN,14,120405.0,120405.0,91200,134500,177800,1,0,0,1.0,1,Full time,Employee,Regular,NaN,Well Placed,C3035 Unum Group,United States of America,Chattanooga,Chattanooga Home Office,NaN,Information Technology,Information Tech,Information Technology,Operations Services,Inactive Cost Centers,Inactive Cost Ctrs,EC1645,NaN,Termination,0,0,0,0,0,1,0,1,SupOrg_00303218,End User Services,Blake Pease,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00302588,Information Technology,Gautam Roy,SupOrg_00303218,End User Services,Blake Pease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portland Home Office,Information Technology (Gautam Roy),Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27120,2019-Q1,1,2019-01-01,Activity,$DPJM,Mike McCleery,Mike McCleery (Terminated),MMcCleery@UNUM.COM,2001-05-01,1986-07-28,Terminate Employee,Job Elimination/Redundancy,No Placement,NaN,0,0,NaN,15 - 20 Years,17.67,55 - 59,59,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,"NO, I DON'T HAVE A DISABILITY",0,NaN,NaN,Bachelors,0,0,2 Leader,1.3 VP & Equivalent,Information Technology,Information Technology Jobs,IT805-USA,"Technology Capability Officer, US (inactive)",NaN,1.00,02-05 Years,"0 year(s), 11 month(s), 30 day(s)",NaN,16,197239.0,197239.0,142400,210050,277700,0,0,0,1.0,1,Full time,Employee,Regular,NaN,High Impact Leader at Current Level,C3035 Unum Group,United States of America,Chattanooga,Chattanooga Home Office,NaN,Information Technology,Information Tech,Information Technology,Office Of CTO,Infrastructure Sr Mgmt,Infrastructure Senior Mgmt,EC0400,NaN,Termination,0,0,0,0,0,1,0,1,SupOrg_00302588,Information Technology,Gautam Roy,4,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00302588,Information Technology,Gautam Roy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chattanooga Home Office,Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103,2019-Q1,1,2019-01-01,Activity,PRDEM,Dave McMahon,Dave McMahon (Terminated),dmcmahon@unum.com,1985-04-08,1985-04-08,Terminate Employee,Job Elimination/Redundancy,No Placement,NaN,0,0,NaN,25+ Years,33.73,60 and over,61,0,Male,NaN,NaN,NaN,White (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Other,0,0,1 Senior Leader,1.3 VP & Equivalent,Information Technology,Information Technology Jobs,IT219-USA,"VP, Technology, US",NaN,3.66,05-10 Years,"3 year(s), 7 month(s), 28 day(s)",NaN,17,235280.0,235280.0,178000,262550,347100,1,0,0,1.0,1,Full time,Employee,Regular,NaN,High Impact Leader at Current Level,C3035 Unum Group,United States of America,Chattanooga,Chattanooga Home Office,NaN,Information Technology,Information Tech,Information Technology,Operations Services,Inactive Cost Centers,Inactive Cost Ctrs,EC1644,NaN,Termination,0,0,0,0,0,1,0,1,SupOrg_00302588,Information Technology,Gautam Roy,4,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00302588,Information Technology,Gautam Roy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chattanooga Home Office,Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39570,2019-Q1,1,2019-01-01,Activity,G3U12,Tim Powell,Tim Powell (Terminated),Tim.POWELL@unum.co.uk,1989-07-24,1989-07-24,NaN,NaN,NaN,NaN,0,0,NaN,25+ Years,29.44,45 - 49,48,0,Male,Male,Heterosexual,He/Him/His,White (United Kingdom) (inactive),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,1,2 Leader,1.3 VP & Equivalent,NaN,Customer Services,L094-UK,Head of Broker Services,NaN,0.00,02-05 Years,"4 year(s), 2 month(s), 30 day(s)",304213.0,16,152906.9,120770.0,87400,118000,148600,1,0,0,1.0,0,Full time,Employee,Regular,NaN,Well Placed,C5094 Unum European Holding Company Limited,United Kingdom,Dorking,Dorking,Surrey,Unum UK,Unum UK Direct,Unum UK Customer Services,Broker Services,Broker_Services,Brkr Srvcs,EC7028,NaN,Transfer Employee,0,0,0,1,0,0,0,0,SupOrg_00293589,Unum UK Customer Services,Liz Walker,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00051934,Unum International,Mark Till,SupOrg_00293589,Unum UK Customer Services,Liz Walker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unum International (Mark Till),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
recordstart = '2019-07-01'
recordend = '2019-12-31'

In [33]:
turnover5 = 'https://services1.myworkday.com/ccx/service/customreport2/unum/DKJ05/RaaS_Trended_Worker_Turnover_Details?IncludeSubOrgs=1&Active=0&Record_Start={0}-08%3A00&Remove_Exclude_From_HC=0&Record_End={1}-08%3A00&SupervisoryOrg%21WID=fad8c8a44c4510541494e34161d00311&format=csv'.format(recordstart,recordend)
with requests.Session() as s:
    download = s.get(turnover5, auth=(username, password))
    decoded_content = download.content.decode('utf-8')
    turnover5 = pd.read_csv(io.StringIO(decoded_content))
    turnover5 = turnover5.set_index('Emplid')

C:\Users\DDY17\Anaconda3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (11,12,13,80) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [34]:
print(turnover5.shape)
turnover5.head()

(83690, 143)

,Year-Quarter,Month,Record_Date,Record_Type,LAN_ID,Preferred_Name,Worker,Work_Email,Hire,OriginalHireAtRecordDate,Term_Event,Term_Category,Term_Reason,Secondary_Term_Reason,Is_Term_90-Day,Is_Term_New_Hire,Is_Rehire_Eligible,Tenure,Years_of_Service,Age_Group,Age,Diverse,Gender,Gender_Identity,Sexual_Orientation,Pronoun,Ethnicity,Hispanic_Latino,Minority,MinorityStatus,Disability,DisabilityStatus,Disability_Self_ID,Veteran,VeteranStatus,MilitaryStatus,Highest_Degree,On_Leave,Active,Management_Level,Job_Level,Job_Family_Group,Job_Family,Job_Code,Job_Profile,Business_Title,YearsInJobAtRecordDate,Years_In_Job,Time_in_Job,Position_ID,Grade,Annual_Salary,Annual_FTE_Salary,Salary_Range_Minimum,Salary_Range_Midpoint,Salary_Range_Maximum,Is_Org_Manager,Is_People_Manager,Direct_Reports,FTE,Exempt,Full_Part_Time,Worker_Type,Employee_Type,Contingent_Type,Potential,Company,Country,Campus,Location,Work_Address_State,Business_Area,Profile_Area,Department,Consolidated_Area,Area,Sub_Area,Cost_Center_ID,Cost_Center,BP_Type,End_Headcount,Hires,Promotion,Transfer_Out,Transfer_In,Termination,Voluntary_Termination,Involuntary_Termination,SupervisoryOrgID,SupervisoryOrg,OrgManager,OrgLevel,OrgLevel01ID,OrgLevel01,OrgLevel01Manager,OrgLevel02ID,OrgLevel02,OrgLevel02Manager,OrgLevel03ID,OrgLevel03,OrgLevel03Manager,OrgLevel04ID,OrgLevel04,OrgLevel04Manager,OrgLevel05ID,OrgLevel05,OrgLevel05Manager,OrgLevel06ID,OrgLevel06,OrgLevel06Manager,OrgLevel07ID,OrgLevel07,OrgLevel07Manager,OrgLevel08ID,OrgLevel08,OrgLevel08Manager,OrgLevel09ID,OrgLevel09,OrgLevel09Manager,OrgLevel10ID,OrgLevel10,OrgLevel10Manager,Manager_Location,Supervisory_Org_L1_Away,Supervisory_Org_L2_Away,Supervisory_Org_L3_Away,Supervisory_Org_L4_Away,Supervisory_Org_L5_Away,Supervisory_Org_L6_Away,Supervisory_Org_L7_Away,Supervisory_Org_L8_Away,Supervisory_Org_L9_Away,Supervisory_Org_L10_Away,Worker_Supervisory_Org_L1,Worker_Supervisory_Org_L2,Worker_Supervisory_Org_L3,Worker_Supervisory_Org_L4,Worker_Supervisory_Org_L5,Worker_Supervisory_Org_L6,Worker_Supervisory_Org_L7,Worker_Supervisory_Org_L8,Worker_Supervisory_Org_L9,Worker_Supervisory_Org_L10
Emplid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100495,2019-Q3,7,2019-07-01,Activity,AYA19,Mahesh Manickam,Mahesh Manickam [C] (Contract Ended),MManickam2@UNUM.COM,2019-03-19,2019-03-19,End Contingent Worker Contract,Voluntary,Unknown,NaN,0,1,NaN,00 - 01 Years,0.28,24 and under,0,0,NaN,NaN,NaN,NaN,NaN,0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,0,NaN,NaN,Contingent Workers,Contingent Worker Jobs,CW001,Contract Service Worker,NaN,0.28,01-02 Years,"0 year(s), 3 month(s), 11 day(s)",NaN,NaN,0.00,0.0,0,0.0,0,0,0,0,1.0,0,Full time,Contingent Worker,NaN,Vendor - Contract Labor,NaN,C3035 Unum Group,United States of America,Chattanooga,Chattanooga Home Office,NaN,Information Technology,Information Tech,Office Of CTO,Risk Mgmt,Risk Management,Risk Mgmt Staff_2,EC0490,NaN,End Contingent Worker Contract,0,0,0,0,0,1,1,0,SupOrg_00306490,Enterprise Security & Risk Management,Marc Bouchard,7,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00302588,Information Technology,Gautam Roy,SupOrg_00319655,Information Security,Matthew Parciak,SupOrg_00219597,Enterprise Information Security - Identity & A...,Marc Bouchard,SupOrg_00306490,Enterprise Security & Risk Management,Marc Bouchard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Enterprise Information Security - Identity & A...,Information Security (Matthew Parciak),Information Technology (Gautam Roy),Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91351,2019-Q3,7,2019-07-01,Activity,BVK16,Eddie Gorman,Eddie Gorman,EGorman@unum.com,2016-10-18,2016-10-18,NaN,NaN,NaN,NaN,0,0,NaN,02 - 05 Years,2.70,30 - 34,34,0,Male,NaN,NaN,NaN,White (Ireland),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,1,5 Individual Contributor,5.2 Professional - Individual Contributor,Information Technology,Information Technology Jobs,IT844-IRE,"UX Designer I, IRE","UX Designer II, IRE",0.00,01-02 Years,"0 year(s), 8 month(s), 29 day(s)",310991.0,11,47217.28,49000.0,38600,55900.0,73200,0,0,0,1.0,1,Full time,Employee,Regular,NaN,NaN,C5020 Unum Ireland Limited,Ireland,Ireland,Carlow,Carlow,Information Technology,Information Tech,UX IT,UX - Info Tech,UX Area,UX.,EC1586,UX IRE,Promote Employee Outbound,0,0,1,0,0,0,0,0,SupOrg_00218705,Information Technology - IRE,Ken O'Brien,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00303910,Information Technology,Padraig O'Neill,SupOrg_00218705,Information Technology - IRE,Ken O'Brien,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carlow,Information Technology (Padraig O'Neill),Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,Unum Executive (Rick McKenney),Unum Group (Rick McKenney),Technology and Transformation (Puneet Bhasin),Information Technology (Padraig O'Neill),Information Technology - IRE (Ken O'Brien),NaN,NaN,NaN,NaN,NaN
93303,2019-Q3,7,2019-07-01,Activity,BFD17,Martin Reilly,Martin Reilly,MReilly@UNUM.COM,2017-06-12,2017-06-12,NaN,NaN,NaN,NaN,0,0,NaN,02 - 05 Years,2.05,30 - 34,30,0,Male,NaN,NaN,NaN,White (Ireland),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,1,5 Individual Contributor,5.2 Professional - Individual Contributor,Information Technology,Information Technology Jobs,IT844-IRE,"UX Designer I, IRE","UX Designer II, IRE",0.00,01-02 Years,"0 year(s), 8 month(s), 29 day(s)",310992.0,11,53658.26,52000.0,38600,55900.0,73200,0,0,0,1.0,1,Full time,Employee,Regular,NaN,Longer Term High Potential,C5020 Unum Ireland Limited,Ireland,Ireland,Carlow,Carlow,Information Technology,Information Tech,UX IT,UX - Info Tech,UX Area,UX.,EC1586,UX IRE,Promote Employee Outbound,0,0,1,0,0,0,0,0,SupOrg_00218705,Information Technology - IRE,Ken O'Brien,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00303910,Information Technology,Padraig O'Neill,SupOrg_00218705,Information Technology - IRE,Ken O'Brien,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carlow,Information Technology (Padraig O'Neill),Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,Unum Executive (Rick McKenney),Unum Group (Rick McKenney),Technology and Transformation (Puneet Bhasin),Information Technology (Padraig O'Neill),Information Technology - IRE (Ken O'Brien),NaN,NaN,NaN,NaN,NaN
100515,2019-Q3,7,2019-07-01,Activity,AYL19,Nedra Price,Nedra Price [C] (Contract Ended),NPrice@UNUM.COM,2019-02-11,2019-02-11,End Contingent Worker Contract,Voluntary,Convert to Employee,NaN,0,1,NaN,00 - 01 Years,0.39,35 - 39,36,1,Female,NaN,NaN,NaN,Not Indicated (United States of America),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,NaN,0,0,NaN,NaN,Contingent Workers,Contingent Worker Jobs,CW003,Temp Worker (short-term),NaN,0.38,02-05 Years,"0 year(s), 4 month(s), 19 day(s)",NaN,NaN,0.00,0.0,0,0.0,0,0,0,0,1.0,0,Full time,Contingent Worker,NaN,Temp Staff,NaN,C3035 Unum Group,United States of America,Baton Rouge,Baton Rouge Home Office,NaN,US Operations,Unum Specialty Business,Unum Dental and Vision,Dental and Vision Operations,Dental_and_Vision_Operations,Dental and Vision Claims,EC3148,NaN,End Contingent Worker Contract,0,0,0,0,0,1,1,0,SupOrg_101887,"Operation Directors, Starmount",Renee Jaszcz,7,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00112942,Unum Group COO,Michael Simonds,SupOrg_00306911,Unum Specialty Lines,Andrea Gordon,SupOrg_00298756,"Operation Directors, Starmount",Paul McLean,SupOrg_00305228,"Operation Directors, Starmount",Catherine Lackey,SupOrg_101887,"Operation Directors, Starmount",Renee Jaszcz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Baton Rouge Home Office,"Operation Directors, Starmount (Catherine Lackey)","Operation Directors, Starmount (Paul McLean)",Unum Specialty Lines (Andrea Gordon),Unum Group COO (Michael Simonds),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75931,2019-Q3,7,2019-07-01,Activity,BQQ13,Robert Hogan,Robert Hogan,RHogan2@UNUM.COM,2014-01-03,2014-01-03,NaN,NaN,NaN,NaN,0,0,NaN,05 - 10 Years,5.49,45 - 49,48,0,Male,NaN,NaN,NaN,White (Ireland),0,0,Non-Minority,0,NaN,NaN,0,NaN,NaN,Diploma/Level 4-5 NVQ/SVQ,0,1,5 Individual Contributor,5.2 Professional - Individual Contributor,Information Technology,Information Technology Jobs,IT794-IRE,"Business Analyst I, IRE","Senior Business Analyst, IRE",0.00,01-02 Years,"1 year(s), 9 month(s), 26 day(s)",310582.0,11,62256.77,60000.0,46300,67100.0,87900,0,0,0,1.0,0,Full time,Employee,Regular,NaN,Near Term High Potential,C5020 Unum Ireland Limited,Ireland,Ireland,Carlow,Carlow,Information Technology,Information Tech,IT Transformation,Digital Ventures and Transformation,Solutions Journey Tech,HR Connect IT,EC1532,IRE Data Analytics,Promote Employee Outbound,0,0,1,0,0,0,0,0,SupOrg_00213165,Data Analytics & Engineering Excellence,Declan McGill,5,SupOrg_Executive,Unum Executive,Rick McKenney,SupOrg_00202594,Unum Group,Rick McKenney,SupOrg_00300846,Technology and Transformation,Puneet Bhasin,SupOrg_00303910,Information Technology,Padraig O'Neill,SupOrg_00213165,Data Analytics & Engineering Excellence,Declan McGill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carlow,Information Technology (Padraig O'Neill),Technology and Transformation (Puneet Bhasin),Unum Group (Rick McKenney),Unum Executive (Rick McKenney),NaN,NaN,NaN,NaN,NaN,NaN,Unum Executive (Rick McKenney),Unum Group (Rick McKenney),Technology and Transformation (Puneet Bhasin),Information Technology (Padraig O'Neill),Data Analytics & Engineering Excellence (Decla...,NaN,NaN,NaN,NaN,NaN

In [35]:
turnovercombined = pd.concat([turnover, turnover2,turnover3, turnover4, turnover5], axis=0)

In [36]:
turnovercombined.to_csv(r'O:\people_analytics\scorecards_kpis\ldp\data_build\all_turnover_combined_ldp.csv')

In [1]:
turnovercombined.head()

NameError: name 'turnovercombined' is not defined